### ISSUE TITLE
plan operation: Real and shadow diffs do not match!

### ISSUE THREAD

**Issue by rata** [hashicorp/terraform#10222]
Hi there,

### Terraform Version
Terraform v0.7.11. Also happened in 0.7.10

### Affected Resource(s)
- aws_eip

But it had happened with several other resources too.

### Panic Output
```
+ module.app11_agenda.aws_eip.static_ip
    allocation_id:     "<computed>"
    association_id:    "<computed>"
    domain:            "<computed>"
    instance:          "i-085e0bbdfd1b26b95"
    network_interface: "<computed>"
    private_ip:        "<computed>"
    public_ip:         "<computed>"
    vpc:               "true"


Plan: 1 to add, 0 to change, 0 to destroy.
Experimental feature failure! Please report a bug.

This is not an error. Your Terraform operation completed successfully.
Your real infrastructure is unaffected by this message.

While running, Terraform sometimes tests experimental features in the
background. These features cannot affect real state and never touch
real infrastructure. If the features work properly, you see nothing.
If the features fail, this message appears.

The following failures happened while running experimental features.
Please report a Terraform bug so that future Terraform versions that
enable these features can be improved!

You can report an issue at: https://github.com/hashicorp/terraform/issues

1 error(s) occurred:

* plan operation: Real and shadow diffs do not match! Real diff:

module.app11_agenda:
  CREATE: aws_eip.static_ip
    allocation_id:     "" => "<computed>"
    association_id:    "" => "<computed>"
    domain:            "" => "<computed>"
    instance:          "" => "i-085e0bbdfd1b26b95"
    network_interface: "" => "<computed>"
    private_ip:        "" => "<computed>"
    public_ip:         "" => "<computed>"
    vpc:               "" => "true" (forces new resource)
module.search.search:

Shadow diff:

module.app11_agenda:
  CREATE: aws_eip.static_ip
    allocation_id:     "" => "<computed>"
    association_id:    "" => "<computed>"
    domain:            "" => "<computed>"
    instance:          "" => "i-085e0bbdfd1b26b95"
    network_interface: "" => "<computed>"
    private_ip:        "" => "<computed>"
    public_ip:         "" => "<computed>"
    vpc:               "" => "true" (forces new resource)


This is not an error. Your terraform operation completed successfully
and your real infrastructure is unaffected by this message.
```

Let me know if you want me to test some version to see if this stop happening, or how I can help. Thanks!

**Comment by rata** [comment]
Here there is another example, using a dyn_record, in case it helps:

```
* plan operation: Real and shadow diffs do not match! Real diff:

module.app11_agenda:
  UPDATE: dyn_record.hostname
    value: "54.146.44.63" => "IPX"
module.search.search:

Shadow diff:

module.app11_agenda:
  UPDATE: dyn_record.hostname
    value: "54.146.44.63" => "IPX"



This is not an error. Your terraform operation completed successfully
and your real infrastructure is unaffected by this message.
```
(replaced the new IP with "IPX", but it is the same IP address the two times)
