### ISSUE TITLE
Question: Variable count of ALB & ALB Target Group & ALB Listener

### ISSUE THREAD

**Issue by owenmorgan** [hashicorp/terraform#11356]
hello, i'm having trouble getting my head around how to achieve this in terraform.. I have a cli that will read a template of a definition of an an AWS ALB, and id like terraform to generate a variable amount of ALBs, listeners and target groups.

so as an example.. i have a template in yaml.

```
      load_balancer:
        - name: alb-name-hw1
          ports:
            - 80:80
            - 9080:9080
            - 81:81
        - name: alb-name-hw2
          ports:
            - 80:80
            - 9080:9080
```
The Cli for this will output this into a tfvars file like so (the cli can change if required):

```
     worker_elb_names = "alb-name-hw1,alb-name-hw2"
     worker_elb_listener_ports = "80;9080;81,80;9080"
     worker_elb_target_ports = "80;9080;81,80;9080"
```

Im trying to create these definitions in terraform.. but the count and assigning the ports to each instance of a aws_alb_target_group and aws_alb_listener will get skewed with anything i attempt. Is there a cleaner way to achieve this? using a map perhaps?

this is what i currently have (with some properties removed).

ALB

```
resource "aws_alb" "web-alb" {
  ....
  count = "${length(split(",", var.elb_names))}"
}
```
Target Group

```
resource "aws_alb_target_group" "web-alb" {
  name     = "${element(split(",", var.elb_names), count.index)}-${element(split(";", element(split(",",var.elb_target_ports),count.index)), count.index)}"
  port     = "${element(split(",", element(split(";",var.elb_target_ports),count.index)), count.index)}"
  count = "${length(split(",", var.elb_target_ports)) + length(split(";",var.elb_target_ports)) - 1}"
}
```
Listener

```
resource "aws_alb_listener" "alb_listener" {
  load_balancer_arn = "${element(aws_alb.web-alb.*.id, count.index)}"
  port              = "${element(split(",", element(split(";",var.elb_listener_ports),count.index)), count.index)}"
  count = "${length(split(",", var.elb_target_ports)) + length(split(";",var.elb_target_ports)) - 1}"
}
```
