### ISSUE TITLE
AzureRM: arm templates don't actually get deleted on terraform destroy

### ISSUE THREAD

**Issue by JamesWoolfenden** [hashicorp/terraform#11789]
I'm provisioning in Azure using azurerm_template_deployment resources and arm templates created for azure.
Creating the templates works fine in Terraform. The issue appears (or in this case doesn't) when i try to destroy templates. Terraform appears to do the action successfully but no resource deletion actually occurs.

### Terraform Version
Terraform v0.8.5

### Affected Resource(s)
- azurerm_template_deployment

### Terraform Configuration Files
```hcl
resource "azurerm_template_deployment" "app" {
  name                = "${var.name}"
  resource_group_name = "${var.resource_group_name}"

  template_body = "${file("./armtemplates/app.json")}"

  deployment_mode = "Incremental"

  parameters = {
    name                    = "${var.name}"
    location                = "${var.location}"
    hostingEnvironment      = "${var.hostingEnvironment}"
    environment             = "${var.environment}"
    hostingPlanName         = "${var.hostingPlanName}"
    serverFarmResourceGroup = "${var.resource_group_name}"
    subscriptionId          = "${var.subscriptionId}"
  }
}

### Expected Behavior
What should have happened?
I'd have expected the resource to have  been destroyed in azure, if not for any errors to be raised.

### Actual Behavior
No errors raised, no resources deleted.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform destroy`
2. check resource.
### Important Factoids
my repo: https://github.com/JamesWoolfenden/automatic-azure-eureka/tree/master/terraform

###IMPORTANT
I have had a related issue deleting resources using the azure cli, that I found whilst investigating the failure to delete via terraform. The related commands (if i had created these objects either via terraform or more directly):

azure resource delete development-terraform-resource-group terraform-app Microsoft.Web/sites -o "2015-06-15"
azure resource delete development-terraform-resource-group terraform-app-service-plan Microsoft.Web/serverFarms -o "2015-06-15"

These commands also appear to delete azure resources but actually do nothing (this is a verified with MS with Azure today).  So the issue may be that you are calling the same api?

**Comment by pmcatominey** [comment]
@JamesWoolfenden ARM templates are a resource of their own, deleting them simply removes the deployment resource and not the resources created/updated by it. Maybe the docs could be updated to highlight this.

**Comment by JamesWoolfenden** [comment]
That would leave orphaned resources in Azure, surely that can be the purpose of the resource. I would imagine destroying a template removes the resources created by the apply and not just history of the templates deployment?
Id then have find some way outside of terraform to destroy those resources and that can't be right?

**Comment by pmcatominey** [comment]
From what I can recall this is the way template deployments work on Azure, you can confirm this by using the CLI.

**Comment by JamesWoolfenden** [comment]
As i stated in the report, the instance of the template - the resource is supposed to be deleted when the template is deleted.

As it is when you delete thru the Azure CLi. e.g.
 azure webapp delete development-terraform-resource-group azure-app-delete

Deletes the template and the resources created by it.

**Comment by pmcatominey** [comment]
I think there's a misunderstanding around templates here, the template resource in terraform wraps the deployments API. When deleting a deployment resource it only removes the record of the deployment and not the resources created by it. The CLI method to test this would be under a deployments or similar sub command.

I've ran into this scenario before and unfortunately the only nice solution is to implement the desired resource as a first class Terraform resource or manage resources at the resource group level when you want to delete resources created by a template.

**Comment by JamesWoolfenden** [comment]
You can use the resource "azurerm_template_deployment" to create app services and app service plans, or any other arm template in the Resource manager. This is great. 

But when you then destroy that template, terraform cannot support the destruction of those resources created in the apply phase?
If that's correct and desired it cannot be used to idempotently provision ARM templates.

**Comment by broomyocymru** [comment]
If you use a unique azurerm_resource_group for your template and create all the resources of the template into that group terraform will destroy the group along with anything in it! Not a fix but hopefully a usable workaround

**Comment by JamesWoolfenden** [comment]
Yeah i know that but if you're sharing a resource group across terraform projects it's not workable. I was creating objects in a resources group->vnet->object, so i'd have to make multiple vnets just to get around the bug. Plus what happens to the state files behind for the objects that didn't but did get destroyed?

**Comment by whiskeyjay** [comment]
This is just to confirm that [the API for deleting an deployment](https://docs.microsoft.com/en-us/rest/api/resources/deployments#Deployments_Delete) doesn't delete associated resources. The Azure portal has the same behavior when deleting deployments.

I believe "azurerm_template_deployment" exists as a workaround for creating Azure resources the native Terraform Azure RM provider doesn't support yet. Terraform only understands the "deployment" as a single resource, but has no idea what is inside the ARM template, hence not too much it can do when the API doesn't delete resources created by the template.

This issue should be resolved by adding native support for the Azure resource types that are currently missing (app service, app service plan), so you don't have to use embedded ARM template in a Terraform configuration.

**Comment by tombuildsstuff** [comment]
Hi @JamesWoolfenden

Thanks for opening this issue.

I'd like to ensure we're all on the same page regarding Terminology here - there's a difference between an ARM Template and an ARM Template Deployment.

An ARM Template is the JSON template which defines one or more Azure Resources (e.g. a Application Insights instance, or an App Service Plan).

The ARM Templates are deployed (either through Terraform or the Azure CLI/Powershell/Azure Portal) through an ARM Template Deployment. This Template Deployment submits the ARM Template to Azure, which internally handles creating the resources from the ARM Template. However, due to the way it's been designed, the ARM Template Deployment itself has no knowledge of the Resources which are managed in the ARM Template.

Coming back to Terraform, the Resource `azurerm_template_deployment` manages an ARM Template Deployment - which calls the same API's used by the Azure CLI / Powershell etc - and polls for the status. This means that we're subject to the same constraints in that we don't know what resources have been created in the ARM Template, and thus we're unable to manage them. Instead, Deleting an ARM Template Deployment actually deletes the reference to the Deployment, but not the underlying resources defined within the Template.

Given the design of the ARM Template Deployment feature, I'd argue this feature is working as designed - and as such I'm going to close this issue.

Having said all of that, I believe there's more we can do to communicate this feature better - and since this issue was opened [the documentation for the `azurerm_template_deployment` resource](https://www.terraform.io/docs/providers/azurerm/r/template_deployment.html#note) has been updated to make this clearer.

In an ideal world, Terraform would support every resource in Azure natively - however whilst we've covered most of the common Resources at this point - we've clearly got some more to go; and I'd expect the need for the `azurerm_template_deployment` resource to diminish as time goes on.

Out of interest, can I ask which Azure Resource(s) you're using ARM Templates to manage, so that I can see if it's possible to support them natively in Terraform?

Thanks!

**Comment by pearcec** [comment]
I am deploying two templates right now

* virtual network gateways both ER and VPN (same template different parameters)
* Microsoft.RecoveryServices/vaults

**Comment by JustinGrote** [comment]
Sorry to comment on a closed thread, but @tombuildsstuff our current primary usecase is sendgrid accounts, for which there is no provisioner equivalent.

My workaround has been to have the template output the relevant resource ID to the output, and add a local-exec destroy provisioner. Note my ARM template below is in YAML which gets converted by terraform, they're just easier to write that way IMHO :)
```yaml
---
"$schema": http://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#
contentVersion: 1.0.0.0
parameters:
  name:
    type: string
  location:
    type: string
  password:
    type: secureString
  email:
    type: string
  firstName:
    type: string
  lastName:
    type: string
  company:
    type: string
  website:
    type: string
  acceptMarketingEmails:
    type: string
    defaultValue: "true"
  plan_name:
    type: string
    defaultValue: free
  plan_publisher:
    type: string
    defaultValue: Sendgrid
  plan_product:
    type: string
    defaultValue: sendgrid_azure
  plan_promotion_code:
    type: string
    defaultValue: ""
resources:
- name: "[parameters('name')]"
  apiVersion: '2015-01-01'
  type: Sendgrid.Email/accounts
  location: "[parameters('location')]"
  plan:
    name: "[parameters('plan_name')]"
    publisher: "[parameters('plan_publisher')]"
    product: "[parameters('plan_product')]"
    promotionCode: "[parameters('plan_promotion_code')]"
  properties:
    password: "[parameters('password')]"
    acceptMarketingEmails: "true"
    email: "[parameters('email')]"
    firstName: "[parameters('firstName')]"
    lastName: "[parameters('lastName')]"
    company: "[parameters('company')]"
    website: "[parameters('website')]"
outputs:
  id:
    type: string
    value: "[resourceId('Sendgrid.Email/accounts', parameters('name'))]"
```
```
resource "azurerm_template_deployment" "sendgrid" {
    name = "sendgrid"
    resource_group_name = "test"
    deployment_mode = "Incremental"
    template_body = "${jsonencode(yamldecode(file("sendgrid.arm.yaml")))}"
    parameters = {
        name="test"
        email="test@testy.net"
        firstName="The"
        lastName="Man"
        password="thisisatest"
        company="Nowhere"
        location="westus2"
        website=""
    }

    provisioner "local-exec" {
        when = "destroy"
        command = "az resource delete --ids ${self.outputs.id}"
    }
}
```

This works great, however it only works if you explicity destroy or count=0 before removing the config, if you remove the config it won't work.

As such, since the "Destroy by ID" API is an option in azure, can't we add a parameter to the provisioner such as destroy_created_resources=true, and have the template resource pull the IDs of the created resources and use the delete API? Then I wouldn't need an azure CLI dependency.

Let me know if I should recreate this as a feature request issue.
