### ISSUE TITLE
Templates loaded from file don't interpolate template variables.

### ISSUE THREAD

**Issue by etiennetremel** [hashicorp/terraform#12719]
Not sure if I'm doing something wrong, but combining templates with interpolation from count doesn't seem to work as expected.
I followed the [Using Templates with Count](https://www.terraform.io/docs/configuration/interpolation.html#using-templates-with-count) from the documentation, but didn't succeed.

### Terraform Version

Terraform v0.8.8

### Affected Resource(s)
- google_compute_instance
- template_file
- google_compute_disk

Problem seems to be coming from the interpolation [element()](https://www.terraform.io/docs/configuration/interpolation.html#element_list_index_)

### Terraform Configuration Files
```hcl
variable "node_count" {
  default = "3"
}

resource "google_compute_disk" "my_instance" {
  count = "${var.node_count}"
  name = "my-instance-${count.index}-data"
  zone = "europe-west1-c"
}

data "template_file" "my_instance" {
  count = "${var.node_count}"
  template = "${file("template.yml")}"

  vars {
    DATA_PD = "${element(google_compute_disk.my_instance.*.name, count.index)}"
  }
}

resource "google_compute_instance" "my_instance" {
  count = "${var.node_count}"
  name = "my-instance-${count.index}"
  machine_type = "g1-small"
  zone = "europe-west1-c"

  disk {
    image = "https://www.googleapis.com/compute/v1/projects/google-containers/global/images/container-vm-v20160217"
  }

  metadata {
    google-container-manifest = "${element(data.template_file.my_instance.*.rendered, count.index)}"
  }

  depends_on = [
    "google_compute_disk.my_instance"
  ]
}
```
**template.yml:**
```yaml
version: v1
kind: Pod
metadata:
  name: instance
spec:
  containers:
  - name: instance
    image: image:1.2.3
    volumeMounts:
    - name: data
      mountPath: /data
  volumes:
  - name: data
    gcePersistentDisk:
      pdName: ${DATA_PD}
      fsType: ext4
```

### Expected Behavior

There is no _google-container-manifest.metadata_ displayed in the state.

### Actual Behavior

After running `terraform plan`, here is the output: https://gist.github.com/etiennetremel/15a126081720ecfcffc51b3ec9d1aabf

### Steps to Reproduce

1. `terraform plan`
