### ISSUE TITLE
AWS CodeBuild Auth Failure

### ISSUE THREAD

**Issue by ingshtrom** [hashicorp/terraform#16278]
### Terraform Version
0.10.7

### Terraform Configuration Files
```hcl
terraform {
  backend "s3" {
    bucket = "my-bucket"
    key = "main-infrastructure_us-east-2.tfstate"
    region = "us-east-2"
    dynamodb_table = "my-table"
  }
  required_version = "= 0.10.7"
}

provider "aws" {
  region = "us-east-2"
}
```

### Debug Output
* [broken build output](https://gist.github.com/ingshtrom/95764a4aa1564884ca7cc6a384e3bfe6)
* for comparison, here is [the successful build output](https://gist.github.com/ingshtrom/c791a9030529e3390902521c8f6bc38c) that uses environment variables to work around the issue, but no TF_LOG env var.

### Crash Output
n/a

### Expected Behavior
Everything should run and the `terraform validate` should be successful. The Task Role should be grabbed from the `AWS_CONTAINER_CREDENTIALS_RELATIVE_URI` environment variable, like [the documentation](https://www.terraform.io/docs/providers/aws/index.html#ecs-and-codebuild-task-roles) says.

### Actual Behavior
Terraform fails to setup the s3 backend.

### Steps to Reproduce
Please list the full steps required to reproduce the issue, for example:
1. `setup codebuild`
2. `terraform apply`

### Important Factoids
I am running this in AWS CodeBuild, which means it is using a Task Role since CodeBuild uses ECS under the hood (from my understanding). 

Here is [my CodeBuild config](https://gist.github.com/ingshtrom/3b193fd0e2239f7b1d484da35f118250) that produces a failed build, assuming the s3 backend will load from the Task Role environment variable. There is nothing special about it. 

Here is [my CodeBuild config](https://gist.github.com/ingshtrom/80b6e65cd991c8d8e6b1ff87e2624c1a) that produces a successful build using the environment variables workaround. The CodeBuild output is linked in the Debug Output section.

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- #8746 => similar ticket from several versions ago, but against the _aws provider_, not the _s3 backend_

**Comment by poorsquinky** [comment]
I'm having the exact same problem with CodeBuild and Terraform 0.10.7, using an S3 back-end.

> Error configuring the backend "s3": No valid credential sources found for AWS Provider.

I can provide any other details if they're needed.

**Comment by jch254** [comment]
I am also facing this issue using Terraform with CodeBuild. I would love to remove my workaround:

```
phases:
  pre_build:
    commands:
      # Workaround until TF supports creds via Task Roles when running on ECS or CodeBuild
      # See: https://github.com/hashicorp/terraform/issues/8746
      - export AWS_ACCESS_KEY_ID=`curl --silent http://169.254.170.2:80$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI | jq -r '.AccessKeyId'`
      - export AWS_SECRET_ACCESS_KEY=`curl --silent http://169.254.170.2:80$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI | jq -r '.SecretAccessKey'`
      - export AWS_SESSION_TOKEN=`curl --silent http://169.254.170.2:80$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI | jq -r '.Token'`
```

Any idea when this will be solved for s3 backend?

Thanks
