### ISSUE TITLE
Old values of resource are used on change/modify.

### ISSUE THREAD

**Issue by BlessJah** [hashicorp/terraform#16299]
When resource attributes are used as other resources arguments, on resource change/modify old attribute values are used.

Example below exhibits that behavior by using old version of `aws_cloudformation_stack.storage.outputs` that does not contain `NewS3Bucket` key. I have checked `lookup` function and square bracket syntax.

Issue is triggered only on `aws_cloudformation_stack` update, not on creation.

### Terraform Version
Terraform v0.10.7

### Terraform Configuration Files
```hcl
variable "aws_access_key" {}
variable "aws_secret_key" {}

provider "aws" {
  access_key = "${var.aws_access_key}"
  secret_key = "${var.aws_secret_key}"
  region     = "eu-west-1"
}

resource "aws_cloudformation_stack" "storage" {
  name = "Storage"
  template_body = "${ file("s3.yml") }"
}

resource "aws_s3_bucket_object" "old" {
  bucket = "${aws_cloudformation_stack.storage.outputs["OldS3Bucket"]}"
  key = "old"
  source = "/dev/null"
}

#resource "aws_s3_bucket_object" "new" {
#  bucket = "${aws_cloudformation_stack.storage.outputs["NewS3Bucket"]}"
#  key = "new"
#  source = "/dev/null"
#}
```

```yaml
---
AWSTemplateFormatVersion: 2010-09-09

Outputs:
  OldS3Bucket:
    Value: !Ref OldS3Bucket
#  NewS3Bucket:
#    Value: !Ref NewS3Bucket

Resources:
  OldS3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      AccessControl: Private
#  NewS3Bucket:
#    Type: "AWS::S3::Bucket"
#    Properties:
#      AccessControl: Private
```

### Debug Output
https://gist.github.com/BlessJah/0f87923ac2d4338061626d432cbef2ba

### Expected Behavior
`aws_cloudformation_stack.storage.outputs` is updated during `apply` run, resources that use it's values (i.e. `aws_s3_bucket_object.new`) may get updated or are created based on values computed during runtime, not before dependencies are updated.

### Actual Behavior
Old values of `aws_cloudformation_stack.storage.outputs` are used causing borh `apply` and `plan` to fail.

### Steps to Reproduce
1. `terraform init`
1. `terraform apply`
1. Uncomment everything in terraform and cloudformation code.
1. `terraform plan` (fail)
1. `terraform apply` (fail)
