### ISSUE TITLE
Execution failed due to configuration error: Lambda was not able to access EC2's API using the Lambda Execution Role to set up the Lambda function.

### ISSUE THREAD

**Issue by AkashShanker** [hashicorp/terraform#16870]
We have been trying to execute a simple lambda function in AWS and we keep running into the error. We have tried adding "ec2.amazonaws.com" as a trusted entity to the role with which the Lambda is running. But we keeping getting this particular error:

"Execution failed due to configuration error: Lambda was not able to access EC2's API using the Lambda Execution Role to set up the Lambda function."

Can someone tell us what basically might be going wrong?

Details: We are working from eu-west-1.

**Comment by hashibot** [comment]
This issue has been automatically migrated to terraform-providers/terraform-provider-aws#2577 because it looks like an issue with that provider. If you believe this is _not_ an issue with the provider, please reply to this issue and let us know.

**Comment by wes3985** [comment]
This is not strictly a terraform provider error. I have never used terraform but am seeing this error with AWS SAM CLI when deploying lambdas through cloud formation. The following yaml works:

```
        - Statement:
            Sid: "ec2resources"
            Effect: Allow
            Action: 
              - "ec2:CreateNetworkInterface"
              - "ec2:AttachNetworkInterface"
              - "ec2:DeleteNetworkInterface"
              - "ec2:DescribeNetworkInterfaces"
              - "ec2:DetachNetworkInterface"
              - "ec2:DescribeSecurityGroups"
              - "ec2:DescribeSubnets"
              - "ec2:DescribeVpcs"
            Resource:
              - "*"
```

The following throws the error even through the subnets and security groups are identical to those in the globals configuration:

```
        - Statement:
            Sid: "ec2resources"
            Effect: Allow
            Action: 
              - "ec2:CreateNetworkInterface"
              - "ec2:AttachNetworkInterface"
              - "ec2:DeleteNetworkInterface"
              - "ec2:DescribeNetworkInterfaces"
              - "ec2:DetachNetworkInterface"
              - "ec2:DescribeSecurityGroups"
              - "ec2:DescribeSubnets"
              - "ec2:DescribeVpcs"
            Resource:
              - "arn:aws:ec2:eu-west-1:acc:security-group/sg-xxxx"
              - "arn:aws:ec2:eu-west-1:acc:subnet/subnet-1"
              - "arn:aws:ec2:eu-west-1:acc:subnet/subnet-2"
              - "arn:aws:ec2:eu-west-1:acc:network-interface/*"
              - "arn:aws:ec2:eu-west-1:acc:vpc/vpc-xyz"
```

Is it possible I am missing a permission? Or a resource from the policy?
