### ISSUE TITLE
Enhancement: Configure backend through environment variables similar to tfvars

### ISSUE THREAD

**Issue by eedwards-sk** [hashicorp/terraform#19300]
### Current Terraform Version
0.11.10

### Use-cases
In a CI pipeline, configuring the terraform commands through environment variables rather than explicit arguments is a highly useful feature.

We currently can provide terraform variable values from the environment by using the `TF_VAR_` prefix.

However, we currently cannot use environment variables to configure either the backend type or the backend config values for the `init` command.

### Attempted Solutions
At the moment, the workaround is to use another tool externally to process environment variables similar to as proposed, and then provide them as explicit args.

### Proposal
I propose we add two new environment variables that can be used to configure the backend during `init`:

**backend type**: `TF_BACKEND_TYPE`

e.g. instead of

```
terraform {
  backend "s3" {
  }
}
```

one could provide

`TF_BACKEND_TYPE=s3 terraform init`

**backend config**: `TF_BACKEND_CONFIG_<var>`

e.g. instead of

```
terraform init \
  -backend-config="bucket=my-bucket"
```

one could provide

`TF_BACKEND_CONFIG_bucket="my-bucket" terraform init`

**Comment by apparentlymart** [comment]
Hi @eedwards-sk! Thanks for sharing this use-case.

This seems like a reasonable idea to me.

One detail I'd like to think some more about is how to helper users understand that these environment variables apply only during `terraform init` and that they can't just reset them between other commands. Right now Terraform explicitly tests to make sure the backend configuration hasn't changed since the last `terraform init` so it can block running other commands until the backend has been re-initialized, to avoid misleading users into thinking they are working against a different configuration and then doing something potentially-destructive like writing changes to the wrong state file.

When we introduced the `TF_WORKSPACE` environment variable (for a similar use-case) the compromise we settled on was that `terraform workspace select` would produce an error if asked to change workspace while the environment variable is set, since otherwise you might be misled into thinking you changed workspace even though the environment variable is overriding it.

I think we'd need to take a similar approach here: during any command that works with the backend, we'd need to check whether these environment variables are still set, incorporate their effect into the resolved backend configuration, and produce an error if anything has changed since the last `terraform init`, requiring the user to run `terraform init` explicitly again to confirm the intended change.

---

With this said, I wonder if the existing `TF_CLI_ARGS_` environment variables mechanism is good enough here. This mechanism allows setting any command line argument for a particular command via the environment, like this:

```
$ export TF_CLI_ARGS_init='-backend=s3 -backend-config="..."'
$ terraform init
```

Terraform will then treat these as additional arguments whenever `terraform init` is run. This doesn't work for all situations due to where Terraform inserts these additional arguments into the list of those given on the command line, but I think it would work here where there are no other arguments anyway.

This mechanism was added specifically to avoid the need to make distinct environment variable analogs to every command line option, and the naming schema `TF_CLI_ARGS_init` makes it explicit (hopefully) that this applies only to the `terraform init` command, avoiding my concern above.

If this approach is functional then I think we'd prefer to stick with this since this gives fewer distinct permutations to document, understand, test, etc.

**Comment by eedwards-sk** [comment]
>One detail I'd like to think some more about is how to helper users understand that these environment variables apply only during terraform init and that they can't just reset them between other commands.

That's a very valid concern. As someone who has mostly used terraform before backends, workspaces, or anything fancy involving state, the init process was new to me, and I quickly learned that backend configuration is an 'init only' process.

I think the behavior became clear to me quickly because I'm working in a ci-pipeline situation where I go from init to a 'plan artifact', so the init wouldn't make sense again anyway since my 'apply' phase requires a plan artifact. For users using an interactive / manual workflow, their onboarding process might be different.

>With this said, I wonder if the existing TF_CLI_ARGS_ environment variables mechanism is good enough here.

Did not know about that one. My only concern is that it becomes a lot uglier of an interface for a user in my use case.

e.g. my configuration from a concourse task is limited to environment variables, so passing backend config down to terraform through concourse -> python -> terraform with my above helper code is as easy as:

```yaml
- name: terraform-plan
  plan:
  - get: source
  - get: concourse-terraform
  - get: concourse-terraform-image
  - task: terraform-plan
    image: concourse-terraform-image
    file: concourse-terraform/tasks/plan.yaml
    input_mapping:
      terraform-source-dir: source
    params:
      TF_WORKING_DIR: source/terraform
      TF_BACKEND_TYPE: s3
      TF_BACKEND_CONFIG_bucket: ((aws_bucket))
      TF_BACKEND_CONFIG_key: ((aws_bucket_key))
      TF_BACKEND_CONFIG_region: ((aws_region))
```

If I understand `TF_CLI_ARGS_init` correctly, it would instead look like this:

```yaml
- name: terraform-plan
  plan:
  - get: source
  - get: concourse-terraform
  - get: concourse-terraform-image
  - task: terraform-plan
    image: concourse-terraform-image
    file: concourse-terraform/tasks/plan.yaml
    input_mapping:
      terraform-source-dir: source
    params:
      TF_WORKING_DIR: terraform-source-dir/testdata/terraform
      TF_BACKEND_TYPE: s3
      TF_CLI_ARGS_init: '-backend-config="bucket=((aws_bucket))" -backend-config="key=((aws_bucket_key))" -backend-config="region=((aws_region))"'
```

So it looks doable, but I feel like there's a lot more room to mess up the configuration since now the end-user has to understand the command line rather than just the parameters.

In addition, this doesn't seem to solve the situation of needing to generate a config file to specify the backend type. e.g. I still have to turn `TF_BACKEND_TYPE: s3` into a `backend.tf` file with `backend "s3 {}"`, so having that as at least a CLI option that I can then set with `TF_CLI_ARGS_init` would be nice.

Although... actually... in your example... `-backend=s3` ...? does that work?

If so [it's undocumented](https://www.terraform.io/docs/commands/init.html), but good to know :)

Thanks for your response.
