### ISSUE TITLE
How to find status/error log on the data template_file.

### ISSUE THREAD

**Issue by sampcoug** [hashicorp/terraform#20514]
### Terraform Version

```
Terraform v0.11.11

```

### Terraform Configuration Files

```hcl
data "template_file" "ct" {
  count = "${var.count}"
  depends_on  = ["data.template_file.etcd_discovery_url"]
  template = "${file("container-linux-config_igntion2.2.0.tpl")}"
  vars {
    hostname = "${var.hostname}"
    shortname = "${var.shortname}"
    docker_repo = "${var.docker_repo}"
    message = "${var.message}"
    etcd_discovery_url = "${file("${var.etcd_discovery_token_file_path}")}",
  }
}

```

### Crash Output

Terraform runs successfully

### Expected Behavior
The template file should get loaded during the Terraform run and complete the configuration desired. 

### Actual Behavior
Terraform run completed but template_file failed to run and there are no errors to see what went wrong. 

### Steps to Reproduce

Please list the full steps required to reproduce the issue, for example:
1. Create a data template file with the configuration below:
```
systemd:
  units:
    - name: update-engine.service         #disable autoupdates that result in autoreboot
      mask: true
    - name: locksmithd.service            #disable autoupdates that result in autoreboot
      mask: true
```

2. Add the piece below to your terraform script to include the template file:
```hcl
data "template_file" "ct" {
  count = "${var.count}"
  depends_on  = ["data.template_file.etcd_discovery_url"]
  template = "${file("container-linux-config_igntion2.2.0.tpl")}"
  vars {
    hostname = "${var.hostname}"
    shortname = "${var.shortname}"
    docker_repo = "${var.docker_repo}"
    message = "${var.message}"
    etcd_discovery_url = "${file("${var.etcd_discovery_token_file_path}")}",
  }
}
```
3. `terraform init`
4. `terraform plan`
5. `terraform apply`
