### ISSUE TITLE
cloud-init failures for aws_launch_template when user data compressed and encoded using template_cloudinit_config

### ISSUE THREAD

**Issue by jreyeshdez** [hashicorp/terraform#20955]
`cloud-init` fails for me every time under the following circumstances: an `aws_launch_template` using `template_cloudinit_config` user data with `base64_encode = true` and `gzip = true` 

In /var/log/cloud-init.log this is the only WARNING message (there are no ERROR messages):

```2019-04-08 11:22:40,097 - __init__.py[WARNING]: Unhandled non-multipart (text/x-not-multipart) userdata: 'b"\\x1f\\x8b\\x08\\x00\\x00\\x00\\x00\\x00\\x00\\xffdUk\\x8f\\xaaJ\\x16\\xfdn\\xd2\\xff\\xa1\\xa6'"...'```

**Terraform Version:**
```
Terraform v0.11.13
+ provider.aws v1.60.0
+ provider.template v2.1.0
```

**Affected Resource(s):**
`aws_launch_template`
`template_cloudinit_config`

**Terraform Configuration Files:**

```hcl
data "template_cloudinit_config" "default_cloud_config" {
  gzip          = true
  base64_encode = true

  part {
    filename     = "demo-main-fast"
    content_type = "text/cloud-config"
    content      = "${file("${path.module}/../../resources/demo-main-fast")}"
  }
}

resource "aws_launch_template" "i3_test_launch_template" {
  name                    = "main-test-fast"
  count                   = "1"
  description             = "test"
  disable_api_termination = false
  ebs_optimized           = true

  iam_instance_profile {
    arn = "${data.aws_iam_instance_profile.node_profile.arn}"
  }

  image_id                             = "${data.aws_ami.ubuntu_bionic.id}"
  instance_initiated_shutdown_behavior = "terminate"
  instance_type                        = "i3.xlarge"
  key_name                             = "${var.key_pair}"

  monitoring {
    enabled = true
  }

  vpc_security_group_ids = ["${var.security_group}"]

  tag_specifications {
    resource_type = "instance"

    tags {
      Name      = "test"
      Creator   = "Terraform"
      Network   = "main"
      Autoscale = 1
      Type      = "demo"
      SyncType  = "fast"
    }
  }

  user_data = "${data.template_cloudinit_config.default_cloud_config.rendered}"
}
```

**Cloud-init File:**

```yaml
#cloud-config
package_update: false

write_files:
  - path: /test.txt
    content: |
      Here is a line.
      Another line is here.

users:
  - name: demo
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDf0q4PyG0doiBQYV7OlOxbRjle026hJPBWD+eKHWuVXIpAiQlSElEBqQn0pOqNJZ3IBCvSLnrdZTUph4czNC4885AArS9NkyM7lK27Oo8RV888jWc8hsx4CD2uNfkuHL+NI5xPB/QT3Um2Zi7GRkIwIgNPN5uqUtXvjgA+i1CS0Ku4ld8vndXvr504jV9BMQoZrXEST3YlriOb8Wf7hYqphVMpF3b+8df96Pxsj0+iZqayS9wFcL8ITPApHi0yVwS8TjxEtI3FDpCbf7Y/DmTGOv49+AWBkFhS2ZwwGTX65L61PDlTSAzL+rPFmHaQBHnsli8U9N6E4XHDEOjbSMRX user@example.com

runcmd:
  - 'echo "Checking if Internet is available. Retrying 30 mins..." ; (curl -f -s -o /dev/null --retry 15 --retry-max-time 1800 http://www.google.com && echo "Google is reachable.") || echo "Google is unreachable - rest of bootup might be broken!"'
  - 'apt-get update ; /usr/bin/cloud-init -d single -n cc_package_update_upgrade_install'
  - touch /test.txt
```
