### ISSUE TITLE
Diffs didn't match during apply

### ISSUE THREAD

**Issue by anders-s** [hashicorp/terraform#22293]
### Terraform Version
```
    Terraform Version: 0.11.14
```

### Terraform Configuration Files
```hcl
resource "aws_emr_cluster" "emr-cluster" {
  name          = "${var.group_name}-redshifter-emr-cluster"
  release_label = "${var.release_label}"
  applications  = ["Spark", "Ganglia", "Livy"]
  log_uri       = "s3://${var.logging_bucket}/${var.group_name}/emr"

  termination_protection            = false
  keep_job_flow_alive_when_no_steps = true

  ec2_attributes {
    key_name                          = "${var.key_name}"
    subnet_id                         = "${var.subnet_ids[0]}"
    emr_managed_master_security_group = "${aws_security_group.emr_master_sg.id}"
    emr_managed_slave_security_group  = "${aws_security_group.emr_slave_sg.id}"
    service_access_security_group     = "${aws_security_group.emr_service_sg.id}"
    instance_profile                  = "${aws_iam_instance_profile.emr_ec2_instance_profile.arn}"
  }

  master_instance_group {
    instance_type = "r5.4xlarge"

    ebs_config {
      size                 = "512"
      type                 = "gp2"
      volumes_per_instance = 1
    }
  }

  core_instance_group {
    instance_type  = "r5.2xlarge"
    instance_count = 1

    ebs_config {
      size                 = "128"
      type                 = "gp2"
      volumes_per_instance = 1
    }
  }

  tags = {
    Name        = "abi"
    Environment = "${var.group_name}"
  }

  bootstrap_action {
    path = "s3://${aws_s3_bucket_object.bootstrap_action.bucket}/${aws_s3_bucket_object.bootstrap_action.key}"
    name = "Cluster Bootstrap Action"
  }

  configurations_json = <<EOF
[
    {
        "Classification": "livy-conf",
        "Properties": {
            "livy.server.session.timeout":"5h"
        }
    },
    {
        "Classification": "spark-defaults",
        "Properties": {
            "maximizeResourceAllocation": "true",
            "spark.pyspark.python": "python3",
            "spark.sql.shuffle.partitions":"4000",
            "spark.reducer.maxReqsInFlight":"1000",
            "spark.network.timeout":"800s",
            "spark.executor.heartbeatInterval":"60s",
            "spark.sql.orc.filterPushdown":"true",
            "spark.sql.orc.splits.include.file.footer":"true",
            "spark.sql.orc.cache.stripe.details.size":"10000",
            "spark.sql.hive.metastorePartitionPruning":"true"
        }
    },
    {
        "Classification": "yarn-site",
        "Properties": {
            "yarn.nodemanager.vmem-pmem-ratio": "4",
            "yarn.nodemanager.pmem-check-enabled": "false",
            "yarn.nodemanager.vmem-check-enabled": "false"
    }
  }
]
EOF

  service_role     = "${aws_iam_role.iam_emr_service_role.arn}"
  autoscaling_role = "${aws_iam_role.iam_emr_autoscaling_role.arn}"

  lifecycle {
    ignore_changes = ["ec2_attributes.subnet_id"]
  }
}

resource "aws_emr_instance_group" "task" {
  cluster_id     = "${aws_emr_cluster.emr-cluster.id}"
  instance_type  = "r5.2xlarge"
  instance_count = 0

  ebs_optimized = true

  ebs_config {
    size                 = "100"
    type                 = "gp2"
    volumes_per_instance = 1
  }

  # TODO: We should use max(on-demand) to bid spot:
  # https://github.com/terraform-providers/terraform-provider-aws/issues/7155
  bid_price = 0.5

  autoscaling_policy = <<EOF
{
"Constraints": {
  "MinCapacity": 0,
  "MaxCapacity": 40
},
"Rules": [
  {
    "Name": "ScaleOutMemoryPercentage",
    "Description": "Scale out if YARNMemoryAvailablePercentage is less than 15",
    "Action": {
      "SimpleScalingPolicyConfiguration": {
        "AdjustmentType": "CHANGE_IN_CAPACITY",
        "ScalingAdjustment": 5,
        "CoolDown": 300
      }
    },
    "Trigger": {
      "CloudWatchAlarmDefinition": {
        "ComparisonOperator": "LESS_THAN",
        "EvaluationPeriods": 1,
        "MetricName": "YARNMemoryAvailablePercentage",
        "Namespace": "AWS/ElasticMapReduce",
        "Period": 300,
        "Statistic": "AVERAGE",
        "Threshold": 15.0,
        "Unit": "PERCENT"
      }
    }
  },
    {
    "Name": "ScaleInMemoryPercentage",
    "Description": "Scale in if YARNMemoryAvailablePercentage is larger than 70",
    "Action": {
      "SimpleScalingPolicyConfiguration": {
        "AdjustmentType": "CHANGE_IN_CAPACITY",
        "ScalingAdjustment": -3,
        "CoolDown": 300
      }
    },
    "Trigger": {
      "CloudWatchAlarmDefinition": {
        "ComparisonOperator": "GREATER_THAN",
        "EvaluationPeriods": 3,
        "MetricName": "YARNMemoryAvailablePercentage",
        "Namespace": "AWS/ElasticMapReduce",
        "Period": 900,
        "Statistic": "AVERAGE",
        "Threshold": 75.0,
        "Unit": "PERCENT"
      }
    }
  }
]
}
EOF
}

```

### Debug Output

https://gist.github.com/anders-s/e6e2c3ba124f9267a3e412c7f9743e2e

### Additional Context

We are using a GitLab CI to build our Terraform infrastructure. One of our resources is an EMR cluster that has a bootstrap action and then applies an instance group. The relevant resources are provided above.

However, we ran into the issue listed here: https://github.com/terraform-providers/terraform-provider-aws/issues/9400

We attempted an extremely hacky fix in our GitLab CI below -- namely, not terraforming the 
`aws_emr_instance_group` resource initially, but only after the rest of the resources are applied. We accomplish this by removing the `.tf` suffix from the file, and then `plan` in our `build` step. Removing the suffix is a lazy way of preventing the resource from building, rather than `target`ing every resource except for this one to plan. (We are working on a script for more elegantly `target`ing resources from a list of ones to ignore.) Then, in the `deploy` step, we `apply` the previous plan; rename the file; and re-`apply`, so that the instance group resource is created, without running into the issue 9400.
 
```
build:
  stage: build
  script:
    - source /bin/externalid_assumerole.sh ${GITLAB_CI_PROVISIONER_ARN} 
    - terraform init
    - terraform validate
    - mv $CI_PROJECT_DIR/resources/emr/emr_task_instance_group.tf $CI_PROJECT_DIR/resources/emr/emr_task_instance_group # EXTREMELY hacky way to get around https://github.com/terraform-providers/terraform-provider-aws/issues/9400
    - terraform plan -out $CI_PROJECT_DIR/plan.tfplan
  artifacts:
    paths:
      - $CI_PROJECT_DIR/resources/emr/emr_task_instance_group
      - $CI_PROJECT_DIR/$CI_COMMIT_REF_NAME/.terraform
      - $CI_PROJECT_DIR/plan.tfplan
    expire_in: 1 week

deploy:
  stage: deploy
  when: manual
  script:
    - terraform apply $CI_PROJECT_DIR/plan.tfplan
    - mv $CI_PROJECT_DIR/resources/emr/emr_task_instance_group $CI_PROJECT_DIR/resources/emr/emr_task_instance_group.tf
    - terraform plan -out $CI_PROJECT_DIR/plan_emr.tfplan
    - terraform apply $CI_PROJECT_DIR/plan_emr.tfplan
  dependencies: [build]
```
### Expected Behavior

The EMR cluster is terraformed and runs its bootstrap action; then, the instance group is attached to it when we `apply` the second time, and find the EMR cluster already created. 

### Actual Behavior

Failure. 

### References

#9400
