### ISSUE TITLE
Property schema of TypeMap with specific argument names as keys

### ISSUE THREAD

**Issue by dikhan** [hashicorp/terraform#22676]
### Current Terraform Version

Terraform v0.12.7 SDK

### Use-cases

I am trying to figure out what would be the best way to represent the following swagger definition in Terraform schema using TypeMap. Both properties in the map contain the same type string.

````
  ExamplePropertyMap:
    title: this property is a map
    type: object
    properties:
      property_one:
        type: string
      property_two:
        type: string
````

### Attempted Solutions

Based on the documentation for the Schema Elem field (https://github.com/hashicorp/terraform/blob/master/helper/schema/schema.go#L169):

````
For a TypeMap, it must be a *Schema with a Type that is one of the primitives: TypeString, TypeBool, TypeInt, or TypeFloat. 
````

Wondering how you can specify argument names for maps so it's not up to the user to provider any key's the want but rather they are already predefined.

Example of map set up extracted from the terraform documentation for the reference:

````
&schema.Schema{
                          Type:        schema.TypeMap,
                          Optional:    true,
                          Elem:        &schema.Schema{Type: schema.TypeString},
                        },
````

### References

https://stackoverflow.com/questions/57725455/is-it-possible-to-define-a-typemap-property-with-specific-argument-names
