### ISSUE TITLE
Configure CLI options (dir, var file(s), state file) per-project/workspace

### ISSUE THREAD

**Issue by OJFord** [hashicorp/terraform#22734]
### Current Terraform Version
```
0.12.8
```

### Use-cases
In my personal use of terraform, as well as professionally (where I didn't start the project), the terraform configuration goes in a sub-directory rather than the git root, from where I'd naturally be and run terraform commands.

In my personal use I have local state and var files inside a different directory, also in the project root. (It's a symlink to dir outside of git.)

#### Makefile
I have a Makefile with `-var-file`, `-state` and `DIR` repeated in the combination taken by each terraform command I use, and then run `make apply` instead of `terraform apply <long args>`

The problems with this:
- annoying to use `make` instead of `terraform` (and easy to forget when I come back to it)
- doesn't work with e.g. `taint`, because I can't pass in what to taint

#### Env var
`TF_CLI_ARGS` is of course another option. If *all* terraform projects you work on have something like an automatically sourced `env` file this is a good option.

The problems with this:
- discovery
- multiple terraform projects

### Proposal
I'd like to be able to set `-var-file`, `-state`, and terraform dir in a `.terraform/conf.yaml`, for example:
```
# project/.terraform/conf.yaml

var-file:
  - relative/to/.terraform
  - /absolute

var:
  specified: inline

# or just: `state: used/for/both`
state:
  in: relative/to/.terraform
  out: /absolute

dir: relative/to/.terraform
```

Though perhaps for big workspace users, per-workspace config would make more sense.

### References

- #15934 discusses 'remembering' the directory from `terraform init`
