### ISSUE TITLE
Provide 'full' docker image for 0.11

### ISSUE THREAD

**Issue by chrisbond** [hashicorp/terraform#24102]
The only `full` version of Terraform on Docker is now 0.12, a number of modules have not yet been updated for the latest version, _please_ can you provide a full version of 0.11 while the community catches up?

**Comment by danieldreier** [comment]
I'm trying to understand the use case for old versions of full on [dockerhub.](https://hub.docker.com/r/hashicorp/terraform/tags) We do provide images on dockerhub going back to 0.6.14 (4 years ago).

As I understand it, these full images are intended for people wanting to develop terraform without having to set up a local go environment. If you just need to run terraform 0.11.x from Docker, the existing 0.11.x series images ought to work.

 If this is still relevant now that 0.12 has been out for a while, can you help me understand your use cases for using the full images vs the regular images?

**Comment by jeff-knurek** [comment]
I can't speak on behalf of needing _old_ images in all versions, but I had a request before to include specific versions as each image type: 
https://github.com/hashicorp/docker-hub-images/issues/62

`packer` is now providing this: https://hub.docker.com/r/hashicorp/packer/tags
where there's `full-1.5.2` AND `1.5.2`

----
providing previous versions to those who haven't upgraded yet is a nice thing to do, but I think providing multiple images going forward is the "right" think to do 😉

**Comment by percygrunwald** [comment]
Another use case:

We are using the `full` image for doing testing of our Terraform modules repo using Terratest (https://terratest.gruntwork.io/). Terratest requires Go, so having an official image with both Terraform and Go installed saves us having to build an image based on the `light` image and installing Go. We generally try to stay in lock-step with Terraform releases, but it would be great if we could specify an exact version of `full` so we can control when we bump to the next release version.

```yml
image:
  name: hashicorp/terraform:full
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/go/bin:/usr/local/go/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
    - 'CGO_ENABLED=0'

before_script:
  - rm -rf .terraform
  - terraform --version
  - go version

stages:
  - format
  - test

terraform_fmt:
  stage: format
  script:
    - RESULT=$(terraform fmt -recursive -diff)
    - echo $RESULT
    - test -z "$RESULT" # See if result was empty

gofmt:
  stage: format
  script:
    - RESULT=$(gofmt -s -l $(find . -name '*.go' -type f -print))
    - echo $RESULT
    - test -z "$RESULT" # See if result was empty

go_test:
  stage: test
  script:
    - go test ./test/ -v -timeout 30m
```

Given this `.gitlab-ci.yml`, as soon as the `full` release tag points to `0.13.0-beta1`, we will be bumped to that version. In this case, that is what we want, but in future we may want to hold out until a non-beta release before our CI/CD pipeline tests against it.
