### ISSUE TITLE
TERRAFORM CRASH - creating resources using Azure DevOps via Extension

### ISSUE THREAD

**Issue by alvaro212** [hashicorp/terraform#25161]
### Terraform Version

```
...Terraform v0.12.26
```

### Terraform Configuration Files

```hcl
# Set Terraform version and state - start

provider "azurerm" {
	version           = "=2.0.0"
	features {
		key_vault {
      		recover_soft_deleted_key_vaults = true
    }
	}
}

terraform {
	
	required_version = ">= 0.12"

	backend "azurerm" {
		storage_account_name         = "__terraformstorageaccount__"
		container_name               = "__terraformcontainer__"
		key                          = "vm.tfstate"
		access_key                   = "__storagekey__"
	   }
}

# Set Terraform version and state - end

# Windows VMs
module windows {
    source = "./WindowsVM"
}

# Linux VMs
module linux {
    source = "./LinuxVM"
 }
[tf-files.zip](https://github.com/hashicorp/terraform/files/4738643/tf-files.zip)

Please see attached files for more detail.
```

### Crash Output

Please see file attached.

### Expected Behavior
 VMs should be created based on a Red Hat 7.8 image. 

### Actual Behavior

Terraform Crash, please see attached logs as it may be too long to show here.. 
### Steps to Reproduce

1. `terraform init`  (this works fine)
2. `terraform plan`  (this works fine up to a certain point where it crashes) Deleting TF state and VMs allows it to work againbut that's not an option I have in PROD. 
### Additional Context

Using TF via Azure Devops with an extension, see extension details below:
2020-06-05T20:47:43.7047492Z Task         : Run Terraform
2020-06-05T20:47:43.7047681Z Description  : Run a Terraform on the build agent
2020-06-05T20:47:43.7047874Z Version      : 2.4.0
2020-06-05T20:47:43.7048039Z Author       : Peter Groenewegen - Xpirit
2020-06-05T20:47:43.7048349Z Help         : [More Information](https://pgroene.wordpress.com/2016/06/14/getting-started-with-terraform-on-windows-and-azure/)

**Comment by danieldreier** [comment]
@alvaro212 I think you may have forgotten to upload your crash log - I don't see it. Can you please attach it? It would be helpful for me determining whether this is a terraform core or azure provisioner issue.

**Comment by abelal83** [comment]
Which extension in Azure DevOps are you using? We use this in our Azure DevOps YAML release and it works perfectly fine.

```yaml
...

pool:
  vmImage: 'ubuntu-latest'
...
- ${{ if eq(parameters.TerraformApply, true) }}:
  - task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-cli.TerraformCLI@0
    displayName: 'Terraform apply --auto-approve'
    inputs:
      command: apply
      workingDirectory: '${{ parameters.WorkingDirectory }}'
      environmentServiceName: ${{ parameters.AzureSubscription }}
...
```
