### ISSUE TITLE
Errors and multiple misbehaviors handling files with cloudinit

### ISSUE THREAD

**Issue by Deltamir** [hashicorp/terraform#25865]
### Terraform Version
```
Terraform version
Terraform v0.13.0
+ provider registry.terraform.io/-/aws v3.2.0
+ provider registry.terraform.io/-/local v1.4.0
+ provider registry.terraform.io/-/template v2.1.2
+ provider registry.terraform.io/hashicorp/aws v3.2.0
+ provider registry.terraform.io/hashicorp/local v1.4.0
+ provider registry.terraform.io/hashicorp/template v2.1.2
```

### Terraform Configuration Files

I tried to create a test file to show the different behavior I got messing with files and cloudinit.
Below is 6 tests using 6 differents way to pass a filename and a file content to a cloudinit script
#### TF File
```
provider "aws" {
  profile = "default"
  region  = "eu-west-3"
}

resource "local_file" "test" {
  filename   = "test"
}

data "template_file" "user_data" {
  template = file("cloud_init.yaml")
  vars = {
    # Passing raw file and using filebase64 func
    test_name1     = "test"
    test1          = filebase64("test")
    # Passing file through local_file attributes (content_base64 and filename)
    test_name2     = local_file.test.filename     
    test2          = local_file.test.content_base64
    # Passing file through local_file attributes but with filebase64 func
    test_name3     = local_file.test.filename     
    test3          = filebase64(local_file.test.filename)
    
    # Same tests but with file instead of filebase64 and content instead of content_base64
    test_name4     = "test"
    test4          = file("test")
    test_name5     = local_file.test.filename
    test5          = local_file.test.content
    test_name6     = local_file.test.filename
    test6          = file(local_file.test.filename)
  }
}

resource "aws_instance" "test_node" {
  ami                         = "ami-09e973def6bd1ad96"
  instance_type               = "t2.micro"
  associate_public_ip_address = true
  user_data                   = data.template_file.user_data.rendered
}
```
#### CloudInit File

Below is the cloudinit test script that I used.
I tried to create and write the file from each tests inputs (in differents locations to prevent overwrite) 
For each test, I tried to create and write using the write_files module and then using the runcmd module
```
#cloud-config
groups:
  - osadmin: [root,sys]
  - hashicorp

# Add users to the system. Users are added after groups are added.
users:
  - default
  - name: terraform
 ...snip...

write_files:
  - path: /opt/writefile_test1_${test_name1}
    content:
      ${test1}
  - path: /opt/writefile_test2_${test_name2}
    content:
      ${test2}
  - path: /opt/writefile_test3_${test_name3}
    content:
      ${test3}
  - path: /opt/writefile_test4_${test_name4}
    content:
      ${test4}
  - path: /opt/writefile_test5_${test_name5}
    content:
      ${test5}
  - path: /opt/writefile_test6_${test_name6}
    content:
      ${test6}

runcmd:
  - sudo touch /opt/runcmd_test1_${test_name1}
  - echo ${test1} | tee /opt/runcmd_test1_${test_name1}
  - sudo touch /opt/runcmd_test2_${test_name2}
  - echo ${test2} | tee /opt/runcmd_test2_${test_name2}
  - sudo touch /opt/runcmd_test3_${test_name3}
  - echo ${test3} | tee /opt/runcmd_test3_${test_name3}
  - sudo touch /opt/runcmd_test4_${test_name4}
  - echo ${test4} | tee /opt/runcmd_test4_${test_name4}
  - sudo touch /opt/runcmd_test5_${test_name5}
  - echo ${test5} | tee /opt/runcmd_test5_${test_name5}
  - sudo touch /opt/runcmd_test6_${test_name6}
  - echo ${test6} | tee /opt/runcmd_test6_${test_name6}
```

#### Test File
Below is the simple test file I tried to write to the AWS instance
```
test
test
test
```
### Debug Output
https://gist.github.com/Deltamir/81acaa93a6466d11c87ee5935db8acbb

### Expected Behavior
I assume that each of the 6 tests should work both with write_files and with runcmd and expect to have 12 files created in the AWS Instance

#### Error 1
Here is a snippet of the Debug Output (cf gist debug1.txt). As you can see, I can't even run Terraform because the test2 variable is unknown
```
Error: failed to render : <template_file>:29,9-14: Unknown variable; There is no variable named "test2". Did you mean "test3"?, and 3 other diagnostic(s)

  on test.tf line 10, in data "template_file" "user_data":
  10: data "template_file" "user_data" {
```
#### Error 2
To follow my tests, I removed the test2 from the TF file and cloudinit
```
[-]    test_name2     = local_file.test.filename
[-]    test2          = local_file.test.content_base64

```
```
[-]  - path: /opt/writefile_test2_${test_name2}
[-]    content:
[-]      ${test2}
[-]  - sudo touch /opt/runcmd_test2_${test_name2}
[-]  - echo ${test2} | tee /opt/runcmd_test2_${test_name2}
```
And I got the same Error (cf gist debug2.txt) concerning test5. Here is a snippet 
```
Error: failed to render : <template_file>:35,9-14: Unknown variable; There is no variable named "test5". Did you mean "test6"?, and 1 other diagnostic(s)

  on test.tf line 10, in data "template_file" "user_data":
  10: data "template_file" "user_data" {
```
#### Misbehavior 1
Once again I removed the test 5 for every file.
Without test2 (.content_base64) and test5 (.content), I was able to get an AWS Instance running and SSH into it. Finally :)
Here is what I got.
Nothing.
```
[ec2-user@ip-172-31-19-201 ~]$ sudo ls /opt
[ec2-user@ip-172-31-19-201 ~]$ sudo ls /opt
```
The cloudinit script was completly broken and did not even run. 

#### Misbehavior 2
After investigation this behavior was caused by the file() function in the TF file.
Once I remove the test4 AND the test6 from every file, as was able to get the cloudiint script to run on boot.
Here is what I got.
```
[ec2-user@ip-172-31-26-68 ~]$ sudo ls /opt
runcmd_test1_test  runcmd_test3_test  writefile_test1_test  writefile_test3_test
[ec2-user@ip-172-31-26-68 ~]$ sudo cat /opt/runcmd_test*
[ec2-user@ip-172-31-26-68 ~]$
[ec2-user@ip-172-31-26-68 ~]$ sudo cat /opt/writefile_test1_test
dGVzdAp0ZXN0CnRlc3QKCg==[ec2-user@ip-172-31-26-68 ~]$
[ec2-user@ip-172-31-26-68 ~]$ sudo cat /opt/writefile_test3_test
dGVzdAp0ZXN0CnRlc3QKCg==[ec2-user@ip-172-31-26-68 ~]$
```
The 4 tests DID run. But the runcmd way was only able to create files, not to write into them.
This is not a major issue since write_file is the module of choice for such action.

### Steps to Reproduce
Use the same files as I did and then it's a classical terraform init, terraform apply
When testing multiple time, it's necessary to recreate the test file as the local_file module will destroy in on terraform destroy.

### Additional Context
I checked if one issue could come from resource local_file overwriting the test file, but it didn't.
I used watch to check the test file during the process. 
(I did destroy it on calling terraform destroy, as expected from the module)
Some test could have been created in a better way and I did't try every combinaison of parameters but I think that beeing able to pass a file to cloudinit only base64-encoded and only with the filebase64 func is not the expected behavior :)
if it is, then maybe it's a feature request more than a bug
