### ISSUE TITLE
GitHub actions for Gcloud: The init command expects at most one argument.

### ISSUE THREAD

**Issue by tomarv2** [hashicorp/terraform#27988]
Github Action for Gcloud Terraform

```
name: 'Terraform CI'

on:
  push:
    branches:
    - develop
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tfremote
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      working-directory: example/base
      run: |
        export TF_LOG=trace
```
### Terraform Version
```
2021/03/05 05:41:27 [INFO] Terraform version: 0.14.7  
2021/03/05 05:41:27 [INFO] Go runtime version: go1.15.6
```

### Debug Output

```
2021/03/05 05:41:27 [INFO] CLI args: []string{"/home/runner/work/_temp/1dbb2cac-854c-44ef-9c7b-1172718134bc/terraform-bin", "init", "-backend-config=bucket=****", "-backend-config=credentials={   type: service_account,   project_id: ****,   private_key_id: ****,   private_key: -----BEGIN", "PRIVATE", "KEY-----nMIIE=n-----END", "PRIVATE", "KEY-----n,   client_email: terraform@****.iam.gserviceaccount.com,   client_id: ****,   auth_uri: https://accounts.google.com/o/oauth2/auth,   token_uri: https://oauth2.googleapis.com/token,   auth_provider_x509_cert_url: https://www.googleapis.com/oauth2/v1/certs,   client_x509_cert_url: https://www.googleapis.com/robot/v1/metadata/x509/terraform%40****.iam.gserviceaccount.com }", "-backend-config=prefix=terraform/****/cloud-functions"}
2021/03/05 05:41:27 [DEBUG] Attempting to open CLI config file: /home/runner/.terraformrc
2021/03/05 05:41:27 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2021/03/05 05:41:27 [DEBUG] ignoring non-existing provider search directory terraform.d/plugins
2021/03/05 05:41:27 [DEBUG] ignoring non-existing provider search directory /home/runner/.terraform.d/plugins
2021/03/05 05:41:27 [DEBUG] ignoring non-existing provider search directory /home/runner/.local/share/terraform/plugins
2021/03/05 05:41:27 [DEBUG] ignoring non-existing provider search directory /usr/local/share/terraform/plugins
2021/03/05 05:41:27 [DEBUG] ignoring non-existing provider search directory /usr/share/terraform/plugins
The init command expects at most one argument.
2021/03/05 05:41:27 [INFO] CLI command args: []string{"init", "-backend-config=bucket=****", "-backend-config=credentials={   type: service_account,   project_id: ****,   private_key_id: ****,   private_key: -----BEGIN", "PRIVATE", "KEY-----nMIIEn-----END", "PRIVATE", "KEY-----n,   client_email: terraform@****.iam.gserviceaccount.com,   client_id: ****,   auth_uri: https://accounts.google.com/o/oauth2/auth,   token_uri: https://oauth2.googleapis.com/token,   auth_provider_x509_cert_url: https://www.googleapis.com/oauth2/v1/certs,   client_x509_cert_url: https://www.googleapis.com/robot/v1/metadata/x509/terraform%40****.iam.gserviceaccount.com }", "-backend-config=prefix=terraform/****/cloud-functions"}

Usage: terraform init [options] [DIR]

  Initialize a new or existing Terraform working directory by creating
  initial files, loading any remote state, downloading modules, etc.

  This is the first command that should be run for any new or existing
  Terraform configuration per machine. This sets up all the local data
  necessary to run Terraform that is typically not committed to version
  control.

  This command is always safe to run multiple times. Though subsequent runs
  may give errors, this command will never delete your configuration or
  state. Even so, if you have important information, please back it up prior
  to running this command, just in case.

  If no arguments are given, the configuration in this working directory
  is initialized.

Options:

  -backend=true        Configure the backend for this configuration.

  -backend-config=path This can be either a path to an HCL file with key/value
                       assignments (same format as terraform.tfvars) or a
                       'key=value' format. This is merged with what is in the
                       configuration file. This can be specified multiple
                       times. The backend type must be in the configuration
                       itself.

  -force-copy          Suppress prompts about copying state data. This is
                       equivalent to providing a "yes" to all confirmation
                       prompts.

  -from-module=SOURCE  Copy the contents of the given module into the target
                       directory before initialization.

  -get=true            Download any modules for this configuration.

  -get-plugins=true    Download any missing plugins for this configuration.
                       This command is a no-op in Terraform 0.13+: use
                       -plugin-dir settings or provider_installation blocks
                       instead.

  -input=true          Ask for input if necessary. If false, will error if
                       input was required.

  -lock=true           Lock the state file when locking is supported.

  -lock-timeout=0s     Duration to retry a state lock.

  -no-color            If specified, output won't contain any color.

  -plugin-dir          Directory containing plugin binaries. This overrides all
                       default search paths for plugins, and prevents the
                       automatic installation of plugins. This flag can be used
                       multiple times.

  -reconfigure         Reconfigure the backend, ignoring any saved
                       configuration.

  -upgrade=false       If installing modules (-get) or plugins, ignore
                       previously-downloaded objects and install the
                       latest version allowed within configured constraints.

  -verify-plugins=true Verify the authenticity and integrity of automatically
                       downloaded plugins.
Error: Terraform exited with code 1.
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.8/x64/bin/tf", line 8, in <module>
    sys.exit(entrypoint())
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/src/cli.py", line 102, in entrypoint
    TerraformWrapper().main()
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/src/cli.py", line 92, in main
    gcloud_plugin.configure_remotestate(self.required_vars, self.var_data)
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/src/tf_gcloud/plugin.py", line 72, in configure_remotestate
    raise Exception("\nThere was an error setting the remote backend for gcloud; aborting")
Exception: 
There was an error setting the remote backend for gcloud; aborting
Error: Process completed with exit code 1.
```
