### ISSUE TITLE
Trying to use "kubernetes" as backend: Failed to configure: No Auth Provider found for name "gcp"

### ISSUE THREAD

**Issue by slashr** [hashicorp/terraform#29369]
### Terraform Version
```
Terraform v1.0.4
on darwin_amd64
+ provider registry.terraform.io/hashicorp/google v3.79.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.4.1
```

### Terraform Configuration Files
```terraform {
  backend "kubernetes" {
    secret_suffix    = "state"
    load_config_file = true
    config_path = "/Users/me/.kube/staging"
    namespace = "default"
  }

  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "3.79.0"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = ">= 2.0"
    }
  }

  required_version = "~> 1.0"
}
```

### Debug Output
2021-08-13T16:26:01.453+0200 [DEBUG] Adding temp file log sink: /var/folders/kk/c3hqpqf91jn2w8vlkqrjlr480000gp/T/terraform-log036996335
2021-08-13T16:26:01.454+0200 [INFO]  Terraform version: 1.0.4
2021-08-13T16:26:01.454+0200 [INFO]  Go runtime version: go1.16.4
2021-08-13T16:26:01.454+0200 [INFO]  CLI args: []string{"/usr/local/bin/terraform", "init"}
2021-08-13T16:26:01.454+0200 [TRACE] Stdout is a terminal of width 106
2021-08-13T16:26:01.454+0200 [TRACE] Stderr is a terminal of width 106
2021-08-13T16:26:01.454+0200 [TRACE] Stdin is a terminal
2021-08-13T16:26:01.454+0200 [DEBUG] Attempting to open CLI config file: /Users/me/.terraformrc
2021-08-13T16:26:01.454+0200 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2021-08-13T16:26:01.454+0200 [DEBUG] ignoring non-existing provider search directory terraform.d/plugins
2021-08-13T16:26:01.454+0200 [DEBUG] ignoring non-existing provider search directory /Users/me/.terraform.d/plugins
2021-08-13T16:26:01.454+0200 [DEBUG] ignoring non-existing provider search directory /Users/me/Library/Application Support/io.terraform/plugins
2021-08-13T16:26:01.454+0200 [DEBUG] ignoring non-existing provider search directory /Library/Application Support/io.terraform/plugins
2021-08-13T16:26:01.455+0200 [INFO]  CLI command args: []string{"init"}

Initializing the backend...
2021-08-13T16:26:01.456+0200 [TRACE] Meta.Backend: built configuration for "kubernetes" backend with hash value 227197921
2021-08-13T16:26:01.456+0200 [TRACE] Preserving existing state lineage "77f26616-400e-0b83-a031-33e25f4f15b1"
2021-08-13T16:26:01.457+0200 [TRACE] Preserving existing state lineage "77f26616-400e-0b83-a031-33e25f4f15b1"
2021-08-13T16:26:01.458+0200 [TRACE] Meta.Backend: working directory was previously initialized for "kubernetes" backend
2021-08-13T16:26:01.458+0200 [TRACE] Meta.Backend: using already-initialized, unchanged "kubernetes" backend configuration
2021-08-13T16:26:01.460+0200 [INFO]  Successfully loaded config file (/Users/me/.kube/staging; default context)
╷
│ Error: Failed to get existing workspaces: Failed to configure: No Auth Provider found for name "gcp"

### Expected Behavior
Terraform should have initialised

### Actual Behavior
Failed to initialize

### Steps to Reproduce
1. `terraform init`

### Additional Context
The Kube config looks like this
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: certdatabase64encoded
    server: https://35.111.11.11
  name: mycluster
kind: Config
preferences: {}
users:
- name: myuser
  user:
    auth-provider:
      config:
        cmd-args: config config-helper --format=json
        cmd-path: /Users/me/Downloads/google-cloud-sdk/bin/gcloud
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp

```

### References
- #26479
