### ISSUE TITLE
Incorrect handling of HEREDOC saved with CRLF with kubernetes_provider

### ISSUE THREAD

**Issue by zabeloliver** [hashicorp/terraform#29623]
Hi, 

i'm using terraform and the kubernetes_provider to provision Tekton-Pipelines into an Openshift-Cluster. In these Pipelines are Tasks which could have scripts init, which are multiline yaml-values. While creating the terraform-files i took the yaml-files out of the cluster and did a yamldecode() to convert them to HCL and saved them. The multilines where converted to HEREDOC.

Here is an example:

```terraform
resource "kubernetes_manifest" "Pipeline" {
  provider = kubernetes

  manifest = {
    "apiVersion" = "tekton.dev/v1beta1"
    "kind"       = "Pipeline"
    "metadata" = {
      "name"      = "sample-pipeline"
      "namespace" = "my-namespace"
      "labels" = {
        "iac" = "terraform"
      }
    }
    "spec" = {
      "params" = [
        {
          "default" = "sample"
          "name"    = "sample-param"
          "type"    = "string"
        }
      ]
      "tasks" = [
        {
          "name" = "sample"
          "taskRef" = {
            "kind" = "ClusterTask"
            "name" = "openshift-client"
          }
          "params" = [
            {
              "name" = "SCRIPT"
              "value" = <<-EOT
                echo line1
                echo line2
                echo line3
              EOT
            }
          ]
        }
      ]
    }
  }
}
```

The result was the following:
```yaml
...
spec:
  params:
    - default: sample
      name: sample-param
      type: string
  tasks:
    - name: sample
      params:
        - name: SCRIPT
          value: "echo line1\r\necho line2\r\necho line3\r\n"
      taskRef:
        kind: ClusterTask
        name: openshift-client
```

While looking into it, i discovered, that my .tf file was saved on Windows with **CRLF**. I saved the .tf-file with **LF** only and applied it again with the following result:

```yaml
...
spec:
  params:
    - default: sample
      name: sample-param
      type: string
  tasks:
    - name: sample
      params:
        - name: SCRIPT
          value: |
            echo line1
            echo line2
            echo line3
      taskRef:
        kind: ClusterTask
        name: openshift-client
```
which is what i expected. 
So i assume, that there is something wrong with the proper handling of line-endings.

### Terraform Version

```
Terraform v1.0.5
on windows_amd64
+ provider registry.terraform.io/hashicorp/kubernetes v2.4.1
```

### Expected Behavior
Proper handling of yaml-file with HEREDOC indepent of with which linending the .tf file was saved. 

### Actual Behavior
LF-works, while CRLF does not.

### Steps to Reproduce
Save example with CRLF
```
terraform plan
terraform apply
```
See wrong YAML.

Save with LF and see the correct one.
