### ISSUE TITLE
terraform 1.1.0: fatal: Remote branch <GIT SHA> not found in upstream origin

### ISSUE THREAD

**Issue by andresusanto** [hashicorp/terraform#30119]
### Terraform Version

```
1.1.0
```

### Terraform Configuration Files

```terraform
module "some_module_name" {
  source           = "git@github.com:andresusanto/repo//modules/some_module?ref=923e51e12c6e5a1c76dd42a59837d5359d6eaa92" # a valid git commit sha

  some_variable = var.some_variable
}

```

### Expected Behavior

Terraform should be able to pull the module from the repo. I have confirmed that it works on terraform 1.0.11.

### Actual Behavior

```
╷
│ Error: Failed to download module
│ 
│ Could not download module "some_module_name"
│ (../modules/test/main.tf:8) source code from
│ "git::ssh://git@github.com/andresusanto/test-repo?ref=923e51e12c6e5a1c76dd42a59837d5359d6eaa92":
│ error downloading
│ 'ssh://git@github.com/andresusanto/test-repo?ref=923e51e12c6e5a1c76dd42a59837d5359d6eaa92':
│ /usr/bin/git exited with 128: Cloning into
│ '.terraform/modules/env.some_module_name'...
│ Warning: Permanently added the ECDSA host key for IP address '140.82.112.4'
│ to the list of known hosts.
│ fatal: Remote branch 923e51e12c6e5a1c76dd42a59837d5359d6eaa92 not found in
│ upstream origin
```

### Steps to Reproduce

Should be able to reproduce this by using any module with `git` source and `ref` pointing to commit sha on terraform 1.1.0.

**Comment by apparentlymart** [comment]
Thanks for reporting this, @andresusanto!

Based entirely on the message (and not any detailed debugging yet) it sounds like Terraform tried to run `git fetch ssh://git@github.com/andresusanto/test-repo 923e51e12c6e5a1c76dd42a59837d5359d6eaa92` (or a similar command using `git clone` with the branch option), rather then just cloning everything and then switching to the branch afterwards. I don't believe we intentionally changed anything in this way but we should investigate whether perhaps our upstream dependency `go-getter` has introduced what might've been intended as an optimization (clone only the requested branch) but that doesn't work for anything that isn't a named ref.

The other possibility here is that the earlier normalization of module source addresses might account for that, but at first glance I can't yet see why that would cause this effect, since clearly the normalization did preserve the `ref=...` argument exactly as you wrote it.

We'll look into this more closely and see if we can reproduce it and then explain what's changed. Thanks again!

**Comment by andresusanto** [comment]
Cheers @apparentlymart !

**Comment by scott-doyland-burrows** [comment]
Same for me, my root module looks like this - so it is just requesting the latest commit.
Reverted to 1.0.11 and it works fine.

```
module "aws_instance" {
  source = "git::https://github.com/[redacted]/terraform-aws-hgrs-ec2.git"
```

```
Error: Failed to download module

Could not download module "aws_instance" (ec2instance.tf:1) source code from
"git::https://github.com/[redacted]/terraform-aws-hgrs-ec2.git": error
downloading 'https://github.com/[redacted]/terraform-aws-hgrs-ec2.git':
/usr/bin/git exited with 128: Cloning into
'.terraform/modules/aws_instance'...
fatal: Remote branch master not found in upstream origin
```

**Comment by amit-disc** [comment]
Should we not always specify ref now? It is defaulting to master,

**Comment by apparentlymart** [comment]
Hi all,

This change in behavior is a bug, so I would not suggest changing your configuration to work around it unless you need to upgrade to Terraform v1.1.0 immediately for any reason. We intend to restore the previous behavior in a later release.

With that said, if you _do_ need or want to upgrade now then setting `?ref=main` (or whatever is the name of your default branch) may be a reasonable workaround, though I'm not sure yet because we've not yet completed a reproduction on our side.

Thanks!

**Comment by apparentlymart** [comment]
I was able to reproduce this against [a repository we typically use for testing module installation](https://github.com/hashicorp/terraform-aws-module-installer-acctest), as follows:

```hcl
module "example" {
  source = "git::https://github.com/hashicorp/terraform-aws-module-installer-acctest?ref=fbad92afe22792b939ceb233acd86ebd57af8fc7"
}
```

```
Initializing modules...
Downloading git::https://github.com/hashicorp/terraform-aws-module-installer-acctest?ref=fbad92afe22792b939ceb233acd86ebd57af8fc7 for example...
╷
│ Error: Failed to download module
│ 
│ Could not download module "example" (module-source-git.tf:2) source code from
│ "git::https://github.com/hashicorp/terraform-aws-module-installer-acctest?ref=fbad92afe22792b939ceb233acd86ebd57af8fc7": error downloading
│ 'https://github.com/hashicorp/terraform-aws-module-installer-acctest?ref=fbad92afe22792b939ceb233acd86ebd57af8fc7': /usr/bin/git exited with 128: Cloning into
│ '.terraform/modules/example'...
│ fatal: Remote branch fbad92afe22792b939ceb233acd86ebd57af8fc7 not found in upstream origin
│ 
╵
```

However, I was not able to reproduce with a URL that lacked any `ref` at all:

```hcl
module "example" {
  source = "git::https://github.com/hashicorp/terraform-aws-module-installer-acctest"
}
```

```
$ terraform init
Initializing modules...
Downloading git::https://github.com/hashicorp/terraform-aws-module-installer-acctest for example...
- example in .terraform/modules/example
- example.child_a in .terraform/modules/example/modules/child_a
- example.child_a.child_b in .terraform/modules/example/modules/child_b

Initializing the backend...

Initializing provider plugins...

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
```

Since this issue was originally about selecting an arbitrary commit instead of a named ref, I'm going to focus on that part (which I've now reproduced) for the moment, but if I learn something along the way that might explain why a "ref-less" source address would return a similar error then I will aim to fix that too. In the meantime, if anyone else can confirm that particular behavior with no `ref` argument at all, I am happy to retry reproduction of that situation with new information.

**Comment by scott-doyland-burrows** [comment]
It will fail with the ```ref```:

```
terraform {
  required_providers {
    aws = {
    }
  }
}

provider "aws" {
  region = "eu-west-2"
}


module "s3bucket" {
  source = "git::https://github.com/[redacted]/terraform-aws-hgrs-s3bucket.git"

  s3bucket_bucket = "qwerty123456"
}
```
This works fine if I run a ```terraform init``` from the terraform CLI manually - I see this:

```
Terraform v1.1.0
on linux_amd64
doylands@AZWEWSH5DB933:~/temp1$ terraform init
Initializing modules...
Downloading git::https://github.com/[redacted]/terraform-aws-hgrs-s3bucket.git for s3bucket...
- s3bucket in .terraform/modules/s3bucket

Initializing the backend...

Initializing provider plugins...
- Finding latest version of hashicorp/aws...
- Installing hashicorp/aws v3.68.0...
- Installed hashicorp/aws v3.68.0 (signed by HashiCorp)
```
It fails if I use the same code but call it via GitHub Actions - my GitHub Actions workflow code is:
```
name: test
on:
  workflow_dispatch:
env:
  TF_IN_AUTOMATION: true
  TF_INPUT: false
  TF_REGION: eu-west-2
  AWS_ACCOUNT_ACCESS_KEY: ${{ secrets.[redacted] }}
  AWS_ACCOUNT_SECRET_KEY: ${{ secrets.[redacted] }}
jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCOUNT_ACCESS_KEY }}
          aws-secret-access-key: ${{ env.AWS_ACCOUNT_SECRET_KEY }}
          aws-region: ${{ env.TF_REGION }}
      - run: |
          PAT=`aws secretsmanager get-secret-value --secret-id [redacted] --query SecretString --output text`
          git config --global url."https://$PAT@github.com".insteadOf https://github.com
          terraform version
          terraform init
```
and the error is:
```
Terraform v1.1.0
on linux_amd64
Upgrading modules...
Downloading git::https://github.com/[redacted]/terraform-aws-hgrs-s3bucket.git for s3bucket...

Error: Failed to download module

Could not download module "s3bucket" (terraform.tf:13) source code from
"git::https://github.com/[redacted]/terraform-aws-hgrs-s3bucket.git": error
downloading 'https://github.com/[redacted]/terraform-aws-hgrs-s3bucket.git':
/usr/bin/git exited with 128: Cloning into '.terraform/modules/s3bucket'...
fatal: Remote branch master not found in upstream origin
```
If I alter my workflow code to specify the older terraform release, then it works:
```
- uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
          terraform_version: 1.0.11
```
