### ISSUE TITLE
in concurrent scenarious lock with gcs backend fails with "Error acquiring the state lock"

### ISSUE THREAD

**Issue by oprudkyi** [hashicorp/terraform#30149]
in cicd scenarios sometimes the same lock is obtained concurrently by few processes, randomly it fails 
restarting failed process fixes error

### Terraform Version
```
Terraform v1.1.0
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v3.90.1
+ provider registry.terraform.io/hashicorp/google-beta v3.90.1
```

### Terraform Configuration Files
```terraform
terraform {
  backend "gcs" {
    bucket = "some-bucket"
    prefix = "some-prefix"
  }
}

```
### Expected Behavior
Lock obtained 

### Actual Behavior
```
Acquiring state lock. This may take a few moments...

Error: Error acquiring the state lock

Error message: 2 errors occurred:
	* writing
"gs://some-bucket/some-prefix/default.tflock"
failed: googleapi: Error 412: At least one of the pre-conditions you
specified did not hold., conditionNotMet
	* storage: object doesn't exist
```
	
### Steps to Reproduce
terraform apply -auto-approve -lock-timeout=30m -no-color

### Additional Context
up to 20 processes may run apply with the same lock file/gcs backend

**Comment by apparentlymart** [comment]
Hi @oprudkyi! Thanks for sharing this bug report.

I just want to confirm that I'm understanding what you were expecting, and what you actually observed.

You used `-lock-timeout=30m` here, so I assume you were intending for Terraform to keep retrying to obtain the lock for up to 30 minutes if it is already held.

But I think you are saying that _sometimes_ (with no discernible pattern) Terraform just fails immediately with this error, without waiting for the 30 minute timeout.

Is that a correct understanding of what you reported here? Thanks!

**Comment by oprudkyi** [comment]
Hi @apparentlymart , 
yes, you are right. instead of waiting 30minutes it crashes in 30 seconds

**Comment by jinlinux** [comment]
Hi,

are there any updates on this? I have run into the same issue.

I am guessing it is a race condition due to GCS eventual consistency?

**Comment by vfiset** [comment]
Hi, we're facing this issue a lot lately where terraform does not respect the lock-timeout and fails instantly with the message in OP's Actual Behavior section.

Anyone has found workaround or steps that could be implemented to alleviate the issue ?

**Comment by PhillyWebGuy** [comment]
Does anyone have a solution? This is a problem with GCP still.

**Comment by oprudkyi** [comment]
@PhillyWebGuy I rerun ci/cd manually :(

**Comment by PhillyWebGuy** [comment]
If I try to run manually/locally. When I run `terraform init` I get this:

```
Initializing the backend...
╷
│ Error: storage.NewClient() failed: dialing: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
```

So I change my backend.tf to look like this:

```
terraform {
  backend "gcs" {
    bucket = "bucket-xxx-tfstate"
    prefix = "terraform/state"
    credentials = "my-credentials-file.json" #<-- Added this
  }
}
```

Once I add that credentials value, then it works. But that doesn't really solve the automated Github Actions solution I'd like to employ. The `terraform init` command does not fail. And it actually creates a `default.tfstate` file but not the `default.tflock` file.

I don't know if this is the problem other people are having, but to summarize:

- Running `terraform init` seems to work with GCP/Github Actions since the error only throws when trying to execute locally
-  Terraform is definitely able to write to the bucket in question because `default.tfstate` gets written -- but not `default.tflock`. 
- Despite the error, the rest of my script does complete and resources get created.

My Github Actions workflow.yaml file:

```
name: 'Terraform CI'

on:
  push:
    branches:
    - develop
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init
      env:
        GOOGLE_CREDENTIALS: ${{secrets.GOOGLE_CREDENTIALS}}

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Plan
      run: terraform plan
      env:
        GOOGLE_CREDENTIALS: ${{secrets.GOOGLE_CREDENTIALS}}
    
    - name: Terraform Apply
      run: terraform apply -auto-approve -lock-timeout=5m
      env:
        GOOGLE_CREDENTIALS: ${{secrets.GOOGLE_CREDENTIALS}}
```

My main.tf

```
resource "google_storage_bucket" "xxxx_0_logs" {
  name          = "xxx-0-logs"
  force_destroy = true
  location      = "US"
  storage_class = "STANDARD"
  versioning {
    enabled = true
  }
}
```
