### ISSUE TITLE
Rendering Issue When Using Complex Data with template_cloudinit_config Data-Provider

### ISSUE THREAD

**Issue by ferricoxide** [hashicorp/terraform#31027]
When using complext input documents to the `template_cloudinit_config` data-provider, the provider is adding spurious, functionality-breaking CRLFs.

My objective in using the `template_cloudinit_config` data-provider is to allow me to maintain my multi-part userData (`cloud-config` and `bash`-based content) as separate, easiliy-lintable objects. The complexity is that I'm trying to push an Ansible playbook as part of a `cloud-config` block's `write_files` payload.

Initially, the rendered output looked correct. However, I found myself unable to login to my resultant EC2s. When I forced the display of hidden characters in my userData (`vi -b <( aws ec2 describe-instance-attribute --attribute userData --query 'UserData.Value' --output text --instance-id <INSTANCE_ID> | base64 -d - | gunzip - )`), it revealed problematic CRLFs (see "actual behavior" below).

### Terraform Version

```
Terraform v1.1.9
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.13.0
+ provider registry.terraform.io/hashicorp/template v2.2.0

```

### Terraform Configuration Files

`userdata.tf`
```terraform
locals {
  yaml_file = templatefile("user_data/playbook.yaml",
    {
      region        = var.region
      ca_bundle     = var.ca_bundle
      ebs_volume_id = aws_ebs_volume.workstation.id
      tools_bucket  = data.terraform_remote_state.buckets.outputs.buckets.tools
      extras_repo  = var.rhui_extras_repo
    }
  )
  cloud_config_file = templatefile("user_data/userData.cloud_config",
    {
      yaml_file = local.yaml_file
    }
  )
  script = file("user_data/userData.sh")
}

data "template_cloudinit_config" "cloud_config_file" {
  gzip          = true
  base64_encode = true
  part {
    content      = local.cloud_config_file
    content_type = "text/cloud-config"
    filename     = "cloud.cfg"
  }
  part {
    content      = local.script
    content_type = "text/x-shellscript"
    filename     = "script.sh"
  }
}
```
`user_data/userData.cloud_config`
```
#cloud-config

write_files:
  # Ensure password-based logins disabled
  - path: '/etc/ansible/hosts'
    content: |-
      localhost ansible_connection=local
    group: 'root'
    owner: 'root'
    permissions: 0644
  - path: '/opt/Ansible/playbook.yaml'
    content: |-
      ${indent(6, yaml_file)}
    group: 'root'
    owner: 'root'
    permissions: 0644
```

My `user_data/playbook.yaml` is basic Ansible playbook content, but contains data I can't post to a public forum

### Debug Output

No error output

### Expected Behavior

The resultant userData should be rendered as basic multi-part mixed-MIME like so:
```
Content-Type: multipart/mixed; boundary="MIMEBOUNDARY"
MIME-Version: 1.0

--MIMEBOUNDARY
Content-Disposition: attachment; filename="cloud.cfg"
Content-Transfer-Encoding: 7bit
Content-Type: text/cloud-config
Mime-Version: 1.0

#cloud-config

system_info:
  default_user:
    name: thjones2
    gecos: Thomas H Jones II (LOCAL)
    lock_passwd: true
    sudo: ["ALL=(root) NOPASSWD:ALL"]
```

### Actual Behavior

Renders with spurious CRLFs on the MIME-headers:

```
Content-Type: multipart/mixed; boundary="MIMEBOUNDARY"
MIME-Version: 1.0^M
^M
--MIMEBOUNDARY^M
Content-Disposition: attachment; filename="cloud.cfg"^M
Content-Transfer-Encoding: 7bit^M
Content-Type: text/cloud-config^M
Mime-Version: 1.0^M
^M
#cloud-config

system_info:
  default_user:
    name: thjones2
    gecos: Thomas H Jones II (LOCAL)
    lock_passwd: true
    sudo: ["ALL=(root) NOPASSWD:ALL"]```
```

### Additional Context

None

### References

None
