### ISSUE TITLE
No way to force literal empty string when that is desired over the default

### ISSUE THREAD

**Issue by dinibu** [hashicorp/terraform#31145]
Hi! 

I'm trying to specify a kubernetes_persistent_volume_claim to a manually defined (i.e. not automatically provisioned) Kubernetes persistent volume. Part of this requires that the storage_class_name attribute should be to be an empty string, as per the [K8S docs](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#class-1):

> A PVC with its storageClassName set equal to "" is always interpreted to be requesting a PV with no class, so it can only be bound to PVs with no class (no annotation or one set equal to ""). A PVC with no storageClassName is not quite the same and is treated differently by the cluster, depending on whether the [DefaultStorageClass admission plugin](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#defaultstorageclass) is turned on.

However, it looks like Terraform K8S provider interprets that as "use the default", which in this case, means that it looks up and uses the default storage class as the field value, and so it does not match with a class-less PV as expected. 

A literal empty string is required to tell Kubernetes that it should match against class-less persistent volumes. Is there any way to set storage_class_name to be an empty string and override the defaulting behavior from the provider?

Thanks in advance for any time and attention you can put to this.

**Comment by dinibu** [comment]
Here are my resource definitions that don't work as expected:

```
resource "kubernetes_persistent_volume" "test_volume" {

  metadata {
    name = "test-volume"
    labels = {
      "manually-provisioned" = "true"
    }
  }
  spec {
    storage_class_name = ""
    access_modes = ["ReadWriteMany"]
    capacity     = {
      storage: "1Gi"
    }
    persistent_volume_source {
    ...
    }
  }
}

resource "kubernetes_persistent_volume_claim" "test_volume_claim" {

  metadata {
    name = "test-volume-claim"
  }
  spec {
    volume_name = kubernetes_persistent_volume.test_volume.metadata[0].name
    storage_class_name = ""
    access_modes = ["ReadWriteMany"]
    resources {
      requests = {
        storage = kubernetes_persistent_volume.test_volume.spec[0].capacity.storage
      }
    }
    selector {
      match_labels = kubernetes_persistent_volume.test_volume.metadata[0].labels
    }
  }
}

```

In my cluster, I have a default storage class defined called nfs-csi, and so the above results in the following PersistentVolumeClaim object YAML:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-volume-claim
  namespace: eliza
spec:
  volumeName: test-volume
  storageClassName: "nfs-csi"
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      "manually-provisioned": "true"
```

Ideally in my use case, the storageClassName should be an empty string.
