### ISSUE TITLE
AWS EC2 resources not terminated properly after terraform destroy (random)

### ISSUE THREAD

**Issue by Fgerthoffert** [hashicorp/terraform#31743]
### Terraform Version

```shell
Terraform v1.0.10
on linux_amd64
Installed via GitHub Action: hashicorp/setup-terraform@v2
```

### Terraform Configuration Files

See here: https://github.com/Fgerthoffert/terraform-issue/tree/main/terraform

### Debug Output

See:
 - [terraform-apply.log](https://github.com/Fgerthoffert/terraform-issue/blob/main/terraform-apply.log): Creation of the environment (no errors)
 - [terraform-destroy.log](https://github.com/Fgerthoffert/terraform-issue/blob/main/terraform-destroy.log): Destruction of the environment (with errors)

### Expected Behavior

Running `terraform apply -destroy` a few hours after the environment has started should result in the full destruction of all resources.

In this setup, there is no human intervention on the resources between creation and destruction.

### Actual Behavior

Some EC2 instances do not get terminated, which results in issues terminating dependant resources, for example:

```
Error: error deleting EC2 Subnet (subnet-03fa7d24d932dd32c): DependencyViolation: The subnet 'subnet-03fa7d24d932dd32c' has dependencies and cannot be deleted.
```

Although not new for us (it was happening once in a while over the past months), this issue has been happening more frequently recently.

We restore functionality by:
 - Connecting the EC2 dashboard, remove the dangling EC2 instances
 - Remove the placement group
 - Run terraform apply -destroy again

Then the next run should be successful (except if that same issue happens again)

### Steps to Reproduce

Sadly this issue is not happening all the time, making it difficult to reproduce.

But a simplified workflow to reproduce should be:
 - terraform init
 - terraform apply
 - wait for some time (our test duration is ~4h)
 - terraform destroy

### Additional Context

Once every few days, an environment is created (by cron, using GitHub Actions):
- Terraform apply creates and starts the environment
- Tests are executed
- A GitHub Actions runner waits for a marker file to be publicly available (indicating tests were complete)

```
  start:
    name: Start Tests
    runs-on: ubuntu-latest
    outputs:
      env_public_domain: ${{ steps.exports.outputs.env_public_domain }}
      bastion_host: ${{ steps.exports.outputs.bastion_host }}
      perf_tests_jahia_url: ${{ steps.exports.outputs.perf_tests_jahia_url }}
      perf_tests_jahia_jrf_run: ${{ steps.exports.outputs.perf_tests_jahia_jrf_run }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/prepare-environment
        with:
          perf_tests_jahia_jfr_run: false    
      - id: exports
        run: | 
          echo "::set-output name=env_public_domain::${ENV_PUBLIC_DOMAIN}"
          echo "::set-output name=bastion_host::${BASTION_HOST}"
          echo "::set-output name=perf_tests_jahia_url::${PERF_TESTS_JAHIA_URL}"
          echo "::set-output name=perf_tests_jahia_jrf_run::${PERF_TESTS_JAHIA_JFR_RUN}"
      - uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}
      - name: Terraform FMT (linting)
        shell: bash
        run: |
          cd terraform/
          terraform fmt
      - name: Terraform init
        shell: bash
        run: |
          cd terraform/
          terraform init -backend-config=./backend.hcl
      - name: Terraform validate
        shell: bash
        run: |
          cd terraform/
          terraform validate
      # Destroy first in case there was a previous environment still running
      - name: Terraform destroy
        shell: bash
        run: |
          cd terraform/
          terraform apply -destroy
      - name: Set environment variables
        # This step is used to handle both scheduled and workflow_dispatch runs
        shell: bash
        run: |
          INPUT_DRY_RUN=${{ github.event.inputs.dry_run }}
          echo "TF_VAR_PERF_TESTS_START_INFRA_ONLY=${INPUT_DRY_RUN:-false}" >> $GITHUB_ENV
          INPUT_JAHIA_IMAGE=${{ github.event.inputs.jahia_image }}
          echo "TF_VAR_DOCKER_JAHIA_IMAGE=${INPUT_JAHIA_IMAGE:-${{ env.WORKFLOW_JAHIA_IMAGE }}}" >> $GITHUB_ENV
          INPUT_TESTS_IMAGE=${{ github.event.inputs.tests_image }}
          echo "TF_VAR_DOCKER_TESTS_IMAGE=${INPUT_TESTS_IMAGE:-${{ env.WORKFLOW_TESTS_IMAGE }}}" >> $GITHUB_ENV   
      - name: Terraform apply
        shell: bash
        run: |
          cd terraform/
          echo "Terraform: TF_VAR_PERF_TESTS_START_INFRA_ONLY=${TF_VAR_PERF_TESTS_START_INFRA_ONLY}"
          echo "Terraform: TF_VAR_DOCKER_JAHIA_IMAGE=${TF_VAR_DOCKER_JAHIA_IMAGE}"
          echo "Terraform: TF_VAR_DOCKER_TESTS_IMAGE=${TF_VAR_DOCKER_TESTS_IMAGE}"
          terraform apply
```

Once the marker is available:
 - artifacts (results and logs) are downloaded 
 - the environment is destroyed via terraform destroy 

```
  stop:
    name: Stop Tests environment
    runs-on: ubuntu-latest
    if: always()
    needs: download
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}
      - name: Terraform init
        shell: bash
        run: |
          cd terraform/
          terraform init -backend-config=./backend.hcl
      - name: Terraform destroy
        shell: bash
        run: |
          cd terraform/
          terraform apply -destroy
```
