### ISSUE TITLE
yamldecode auto sort keys alphabetically 

### ISSUE THREAD

**Issue by robk9e** [hashicorp/terraform#31870]
### Terraform Version

```shell
1.3.0
```

### Terraform Configuration Files

```
yamldecode("{c: &foo [1, 2, 3], b: *foo}")
{
  "b" = [
    1,
    2,
    3,
  ]
  "c" = [
    1,
    2,
    3,
  ]
}
```

### Debug Output

```
yamldecode("{c: &foo [1, 2, 3], b: *foo}")
{
  "b" = [
    1,
    2,
    3,
  ]
  "c" = [
    1,
    2,
    3,
  ]
}
```

### Expected Behavior

I'd expect yamldecode to honor the order presented on my .yaml file like:

```
yamldecode("{c: &foo [1, 2, 3], b: *foo}")
{
  "c" = [
    1,
    2,
    3,
  ]
  "b" = [
    1,
    2,
    3,
  ]
}
```

### Actual Behavior

It is always sorting the keys and causing drift in my azure application policy configuration.

### Steps to Reproduce

```
terraform console 
yamldecode("{c: &foo [1, 2, 3], b: *foo}")
```

**Comment by apparentlymart** [comment]
Hi @robk9e,

YAML mappings are not order-sensitive, and neither is Terraform's map data type, so Terraform must choose an arbitrary order to use when serializing map elements and it uses a lexical sort by key as that sort order. Terraform is therefore working as intended here.

However, I assume there's some underlying problem you've encountered that caused you to open this issue. Can you say more about why it matters what order the keys are serialized in? You mentioned that this is causing some drift but I'd like to know more specifically what resource type is reporting that drift and what exactly it's reporting. When there are two equally-valid ways to write the same information it's typically the provider's responsibility to implement a rule which avoids classifying such a change as drift, so you may have found a bug in a provider but I can't be sure without seeing a more realistic example.

**Comment by robk9e** [comment]
Hi @apparentlymart, thank you for your prompt reply I really appreciate it!

This is my case:

I need to create and maintain azure firewall rules using terraform and we found that the best approach would be keeping the rules in separated yaml files like this below:

rules.yaml
```
generic-application-rules:
  type: "application"
  action: "Allow"
  priority: 1007
  rules:
    rule-a-first:
      destination_fqdns: ["www.rule-a-first.com"]
      protocols:
        - port: 443
          type: "Https"
        - port: 80
          type: "Http"
      source_addresses: ["172.16.0.0/24"]
```

So, basically whenever my terraform code runs, it parses the yaml files using yamlcode and create the rules for me. Please find below the sample code:

Load the file
```
locals {
  firewall_rule_files = flatten(
    [
      concat(
        [
          for file in try(fileset(var.data_folder, "**/*.yaml"), []) :
          "${path.root}/${var.data_folder}/${file}"
        ]
      )
    ]
  )
  firewall_rules = merge(
    [
      for config_file in local.firewall_rule_files :
      try(yamldecode(file(config_file)), {})
    ]...
  )
}

```
Create the azure firewall rule
```
resource "azurerm_firewall_policy_rule_collection_group" "DefaultApplicationRuleCollectionGroup" {

  count              = length(local.firewall_rules) > 0 ? 1 : 0
  name               = var.name
  firewall_policy_id = var.firewall_policy_id
  priority           = var.priority

  dynamic "application_rule_collection" {

    for_each = { for k, v in local.firewall_rules : k => v if v.type == "application" }
    content {
      action   = application_rule_collection.value.action
      name     = application_rule_collection.key
      priority = application_rule_collection.value.priority

      dynamic "rule" {
        for_each = application_rule_collection.value.rules
        content {
          destination_addresses = try(rule.value.destination_addresses, null)
          destination_fqdn_tags = try(rule.value.destination_fqdn_tags, null)
          destination_urls      = try(rule.value.destination_urls, null)
          name                  = try(rule.key, null)
          terminate_tls         = try(rule.value.terminate_tls, null)
          web_categories        = try(rule.value.web_categories, null)
          destination_fqdns     = try(rule.value.destination_fqdns, null)
          dynamic "protocols" {
            for_each = rule.value.protocols
            content {
              type = protocols.value.type
              port = protocols.value.port
            }
          }
          source_addresses = try(rule.value.source_addresses, null)
          source_ip_groups = try(rule.value.source_ip_groups, null)
        }
      }
    }
  }
```

It will generate the following output:

```
providers/Microsoft.Network/firewallPolicies/DefaultFirewallPolicy/ruleCollectionGroups/DefaultApplicationRuleCollectionGroup"
        name               = "DefaultApplicationRuleCollectionGroup"
        # (2 unchanged attributes hidden)

      + application_rule_collection {
          + action   = "Allow"
          + name     = "generic-application-rules"
          + priority = 1007

          + rule {
              + destination_fqdns = [
                  + "www.rule-a-first.com",
                ]
              + name              = "rule-a-first"
              + source_addresses  = [
                  + "172.16.0.0/24",
                ]

              + protocols {
                  + port = 443
                  + type = "Https"
                }
              + protocols {
                  + port = 80
                  + type = "Http"
                }
            }
        }
        # (2 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

Now I add a new rule named **rule-c-second** and till here all good - as expected the rule **rule-c-second** is placed at the second place :

```
generic-application-rules:
  type: "application"
  action: "Allow"
  priority: 1007
  rules:
    rule-a-first:
      destination_fqdns: ["www.rule-a-first.com"]
      protocols:
        - port: 443
          type: "Https"
        - port: 80
          type: "Http"
      source_addresses: ["172.16.0.0/24"]
    rule-c-second:
      destination_fqdns: ["www.rule-c-second.com"]
      protocols:
        - port: 443
          type: "Https"
        - port: 80
          type: "Http"
      source_addresses: ["172.16.0.0/24"]

```

```
/providers/Microsoft.Network/firewallPolicies/DefaultFirewallPolicy/ruleCollectionGroups/DefaultApplicationRuleCollectionGroup"
        name               = "DefaultApplicationRuleCollectionGroup"
        # (2 unchanged attributes hidden)

      ~ application_rule_collection {
            name     = "generic-application-rules"
            # (2 unchanged attributes hidden)

          + rule {
              + destination_fqdns = [
                  + "www.rule-c-first.com",
                ]
              + name              = "rule-c-first"
              + source_addresses  = [
                  + "172.16.0.0/24",
                ]

              + protocols {
                  + port = 443
                  + type = "Https"
                }
              + protocols {
                  + port = 80
                  + type = "Http"
                }
            }
            # (1 unchanged block hidden)
        }
        # (2 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```


But once I have the resources created and I wanted to add third rule at the third place, the yamldecode will re-sort the keys and cause a "drift" - I say drift because it makes the azurerm see this change not only as adding new rule but also as a re-ordering, misleading and messing up with the output. Here it add it in between rule-a-first and  rule-c-second looking like:

- rule-a-first
- rule-b-third
- rule-c-second

Instead of: 
- rule-a-first
- rule-c-second
- rule-b-third

rules.yaml:

```
generic-application-rules:
  type: "application"
  action: "Allow"
  priority: 1007
  rules:
    rule-a-first:
      destination_fqdns: ["www.rule-a-first.com"]
      protocols:
        - port: 443
          type: "Https"
        - port: 80
          type: "Http"
      source_addresses: ["172.16.0.0/24"]
    rule-c-second:
      destination_fqdns: ["www.rule-c-first.com"]
      protocols:
        - port: 443
          type: "Https"
        - port: 80
          type: "Http"
      source_addresses: ["172.16.0.0/24"]
    rule-b-third:
      destination_fqdns: ["www.rule-b-third.com"]
      protocols:
        - port: 443
          type: "Https"
        - port: 80
          type: "Http"
      source_addresses: ["172.16.0.0/24"]  
   ```

Output:
```
providers/Microsoft.Network/firewallPolicies/DefaultFirewallPolicy/ruleCollectionGroups/DefaultApplicationRuleCollectionGroup"
        name               = "DefaultApplicationRuleCollectionGroup"
        # (2 unchanged attributes hidden)

      ~ application_rule_collection {
            name     = "generic-application-rules"
            # (2 unchanged attributes hidden)

          ~ rule {
              ~ destination_fqdns     = [
                  - "www.rule-c-first.com",
                  + "www.rule-b-third.com",
                ]
              ~ name                  = "rule-c-second" -> "rule-b-third"
                # (7 unchanged attributes hidden)

                # (2 unchanged blocks hidden)
            }
          + rule {
              + destination_fqdns = [
                  + "www.rule-c-first.com",
                ]
              + name              = "rule-c-second"
              + source_addresses  = [
                  + "172.16.0.0/24",
                ]

              + protocols {
                  + port = 443
                  + type = "Https"
                }
              + protocols {
                  + port = 80
                  + type = "Http"
                }
            }
            # (1 unchanged block hidden)
        }
        # (2 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

The expected behavior: yamldecode respect the order I defined as per the yaml file.

This is the closes issue I found in the github the resembles my case:
https://github.com/hashicorp/terraform/issues/29436
