### ISSUE TITLE
Allow for local terraform plan output when Terraform Cloud Execution Mode is set to Remote

### ISSUE THREAD

**Issue by git-benjamin** [hashicorp/terraform#32138]
### Terraform Version

```shell
Terraform v1.3.3
```

### Use Cases

Issue:
- Attempting "terraform plan -out" will return "The "remote" backend does not support saving the generated execution plan locally at this time."

Feature Use Case:
- Allowing an output of a plan or speculative plan will enable Terraform Cloud users with "remote" execution to better run compliance tests, unit tests, and without compromising on the state file management.

Context:
- We have a functioning CICD pipeline utilising GitHub Actions and Terraform Cloud to deploy Snowflake resources.
- We wish to add policy as code utilising Open Policy Agent (conftest) that will run on a push on GitHub actions.
- Conftest requires an output of the Terraform Plan to run conftest policies against.

### Attempted Solutions

We have changed Terraform Cloud to "local" execution and output the state file in GitHub Actions for testing which works as expected. An extract of our GitHub actions/workflow below.

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=temp_plan -lock=false

      - name: Terraform Show
        id: show
        run: terraform show -json ./temp_plan > ./temp_json.json

      - name: Compliance Checks
        uses: addnab/docker-run-action@v3
        with:
          image: openpolicyagent/conftest:latest
          options: -v ${{ github.workspace }}:/build
          run: |
            cd /build
            conftest test -o github temp_json.json

**Comment by git-benjamin** [comment]
Hi @apparentlymart - thanks for the detailed response! 😊

We're currently using [Terraform via GitHub Actions](https://github.com/hashicorp/setup-terraform) as per below.

```
name: "Deploy"

on:
  push:
    branches:
      - main

jobs:
  snowflake-terraform-demo:
    name: "Terraform Tests & Apply"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          terraform_wrapper: false
```

I made a change to my local configuration then ran `terraform plan` followed by
`curl   --header "Authorization: Bearer $TOKEN"   --header "Content-Type: application/vnd.api+json"   https://app.terraform.io/api/v2/workspaces/$WORKSPACE_ID/runs > runs.json`. 

It looks like there is no run with the correct datetime in the .JSON. I'm assuming the API endpoint can only retrieve the execution plan of plan-only runs made via the Terraform API and possibly the plans from Terraform CLI of applied states.
