### ISSUE TITLE
templatefile $ escape removes whole sequence

### ISSUE THREAD

**Issue by atamgp** [hashicorp/terraform#32359]
### Terraform Version

```shell
Terraform v1.2.8
on linux_amd64
+ provider registry.terraform.io/gavinbunney/kubectl v1.14.0
+ provider registry.terraform.io/hashicorp/aws v4.38.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/external v2.2.3
+ provider registry.terraform.io/hashicorp/helm v2.7.1
+ provider registry.terraform.io/hashicorp/kubernetes v2.15.0
+ provider registry.terraform.io/hashicorp/local v2.2.3
+ provider registry.terraform.io/hashicorp/null v3.2.0
+ provider registry.terraform.io/hashicorp/random v3.4.3
+ provider registry.terraform.io/hashicorp/tls v4.0.4
```

### Terraform Configuration Files

```
resource "null_resource" "logging_operator_config" {
  provisioner "local-exec" {
    command     = <<-EOF
      cat <<! | ${local.kubectl} replace -f- 
      ${self.triggers.template}
      !
    EOF
    interpreter = ["/bin/sh", "-c"]
    environment = {
      KUBERNETES_TOKEN  = data.aws_eks_cluster_auth.cluster.token
      KUBERNETES_SERVER = data.aws_eks_cluster.cluster.endpoint
    }
  }

  triggers = {
    template = templatefile("${path.module}/kubernetes-manifests/logging-operator.yaml", {
      controlNamespace = local.apps.logging-operator.namespace
    })
  }
```

template file:
```
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
  name: default
  namespace: ${controlNamespace}
spec:
  file:
    path: /tmp/logs/$${tag}/%Y/%m/%d.%H.%M
    append: true
    buffer:
      timekey: 1m
      timekey_wait: 10s
      timekey_use_utc: true
```

### Debug Output

nothing

### Expected Behavior

path: /tmp/logs/$${tag}/%Y/%m/%d.%H.%M

### Actual Behavior

2022-12-08 12:27:20 +0000 [error]: config error file="/fluentd/etc/fluent.conf" error_class=Fluent::ConfigError error="Parameter 'path: /tmp/logs//%Y/%m/%d.%H.%M.log' doesn't have tag placeholder"

### Steps to Reproduce

terraform apply
