### ISSUE TITLE
feature request: new built-in function base64(string)

### ISSUE THREAD

**Issue by glerchundi** [hashicorp/terraform#3320]
I would like to include in a cloud-config (which is formatted using YAML) section my custom certification authority certificate, which contains newlines. If I use directly with ${file} cloud-config will fail parsing.

What do you think if we can make a function like base64("mystring") which interpolates to the encoded base64 format?

Use-case:

```
#cloud-config

[...]

write_files:
  - path: "/etc/ssl/etcd/ca-chain.cert.pem"
    permissions: "0600"
    owner: "etcd"
    encoding: "base64"
    content: |
      ${base64(file("etcd-ca-chain.cert.pem"))}
```

WDYT?
