### ISSUE TITLE
Kubernetes state backend uses private label keys

### ISSUE THREAD

**Issue by sftim** [hashicorp/terraform#33949]
### Terraform Version

```shell
v1.5.6
```

### Terraform Configuration Files

n/a

### Debug Output

n/a

### Expected Behavior

When storing state into Kubernetes, Terraform (and clones) should use label and annotation keys prefixed with a DNS domain.

Plausible example:
...
   metadata:
     labels:
        app.kubernetes.io/managed-by: terraform
        state.terraform.io/used-for-state-storage: "true"
        state.terraform.io/name-suffix: tfstate
        state.terraform.io/workspace-name: default
```

### Actual Behavior

Actual example:
```yaml
...
   metadata:
     labels:
        app.kubernetes.io/managed-by: terraform
        tfstate: "true"
        tfstateSecretSuffix: tfstate
        tfstateWorkspace: default
```

### Steps to Reproduce

- Set up a Kubernetes cluster
- Set up Terraform to store state into that cluster
- `apply` some infrastructure code
- `kubectl get secrets --all-namespaces`
