### ISSUE TITLE
Incorrect indentation with string interpolation

### ISSUE THREAD

**Issue by ademar-prothon** [hashicorp/terraform#34451]
### Terraform Version

```shell
Terraform v1.6.6
on linux_amd64
```

### Terraform Configuration Files

Module call :

```terraform
module "argocd" {
  source                  = "./modules/argocd"
  entrypoint_chart_values = <<-EOT
    global:
      env: ${var.environment}
  EOT
}
```
Resource in the module :

```terraform
output "my_helm_chart_values" {
    value = <<-EOT
      applications:
        - name: entrypoint
          namespace: argocd
          project: default
          source:
            targetRevision: HEAD
            helm: 
              valuesObject:
                ${var.entrypoint_chart_values}
          destination:
            server: https://kubernetes.default.svc
      EOT
}

```

### Debug Output

    <<-EOT
                applications:
                  - name: entrypoint
                    namespace: argocd
                    project: default
                    source:
                      repoURL: repoURL
                      targetRevision: HEAD
                      path: mypath
                      helm: 
                        valuesObject:
                          global:
                  env: envname
                
                    destination:
                      server: https://kubernetes.default.svc
                      namespace: entrypoint
            EOT,

### Expected Behavior

Values of helm chart should be

```yaml
applications:
  - name: entrypoint
    namespace: argocd
    project: default
    source:
      repoURL: my-repo-url
      targetRevision: HEAD
      path: charts/my-chart
      helm: 
        valuesObject:
          global:
             env: my-variable-value
    destination:
      server: https://kubernetes.default.svc
      namespace: entrypoint
```

### Actual Behavior

Values are, interpolation is badly indented
```yaml
applications:
  - name: entrypoint
    namespace: argocd
    project: default
    source:
      repoURL: my-repo-url
      targetRevision: HEAD
      path: charts/my-chart
      helm: 
        valuesObject:
          global:
  env: my-variable-value

    destination:
      server: https://kubernetes.default.svc
      namespace: entrypoint
```

### Steps to Reproduce

1. `tf init`
2. `tf plan`
