### ISSUE TITLE
Provider produced inconsistent result after apply creating PVC

### ISSUE THREAD

**Issue by joerecra** [hashicorp/terraform#36367]
### Terraform Version

```shell
2.35.1
```

### Terraform Configuration Files

my `pvc.yaml`
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: coderoot-pvc-smb-v1
  namespace: apps
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: coderoot-smb-v1
  resources:
    requests:
      storage: "1024Gi"
  volumeName: coderoot-pv-smb-v1
```
my `pvc resource`
```
resource "kubernetes_manifest" "coderoot_pvc" {
  manifest = yamldecode(templatefile("./fsx_coderoot/pvc.yaml", {
    FSX_CODEROOT_IP = data.aws_fsx_windows_file_system.fsx_coderoot.preferred_file_server_ip
    STORAGE_SIZE    = data.aws_fsx_windows_file_system.fsx_coderoot.storage_capacity
  }))
  computed_fields = ["spec.resources.requests.storage", "metadata.annotations"]
  lifecycle {
    ignore_changes = [manifest.spec.resources.requests.storage]
  }
}
```

### Debug Output

```
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to kubernetes_manifest.coderoot_pvc, provider
│ "provider[\"registry.terraform.io/hashicorp/kubernetes\"]" produced an
│ unexpected new value: .object.spec.resources.requests["storage"]: was
│ cty.StringVal("1024Gi"), but now cty.StringVal("1Ti").
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
```

### Expected Behavior

It shouldn't return any error because im using computed_fields and ignore_changes

### Actual Behavior

unexpected new value: cty.StringVal("1024Gi"), but now cty.StringVal("1Ti").

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`
