### ISSUE TITLE
Builtin support for templates

### ISSUE THREAD

**Issue by errordeveloper** [hashicorp/terraform#642]
When supplying `user_data` to a host, it's desirable to have input that can be planned/tested ahead of resource creation.

It specifically makes sense with static environment files and Cloud Config.

**Comment by korya** [comment]
For everyone who uses CoreOS and wants to parametrize `cloud-config.yml`.

I've found a genious solution at https://github.com/emmanuel/coreos-skydns-cloudformation:
 - use YAML anchors and aliases to parametrize `cloud-config`
 - [coreos-cloudinit](https://github.com/coreos/coreos-cloudinit) uses [go-yaml](https://github.com/go-yaml/yaml) supporting the feature

So in your terraform config define your anchors, it should look like [this](https://github.com/emmanuel/coreos-skydns-cloudformation/blob/master/services/aws.services.tf#L23-L35):
```tf
resource "aws_launch_configuration" "service" {
  ...
  user_data = <<USER_DATA
#cloud-config

dynamic:
  fleet_metadata: &FLEET_METADATA
    metadata: instance_type=${var.aws_instance_type},public_ip=$public_ipv4,region=${var.aws_region},role=service
  discovery_url: &ETCD_DISCOVERY_URL
    discovery: ${var.etcd_discovery_url}
${file("cloud-config.yaml")}
USER_DATA
}
```

Then in your base `cloud-config.yml` use this anchors in the appropriate place, it should look like [this](https://github.com/emmanuel/coreos-skydns-cloudformation/blob/master/services/cloud-config.yaml#L4-L10):
```yml
coreos:
  fleet:
    <<: *FLEET_METADATA
    public-ip: $private_ipv4
  etcd:
    <<: *ETCD_DISCOVERY_URL
    addr: $private_ipv4:4001
    peer-addr: $private_ipv4:7001
  units:
    ...
```
The credit goes to @emmanuel.
