### ISSUE TITLE
Support Google CloudSQL Second Generation instance type

### ISSUE THREAD

**Issue by evandbrown** [hashicorp/terraform#8943]
Second Generation instance types became generally available in August 16 (https://cloudplatform.googleblog.com/2016/08/Cloud-SQL-Second-Generation-performance-and-feature-deep-dive.html). Modify the Cloud SQL provider to support this instance type.

**Comment by csainty** [comment]
I'd love to see this included.
In particular I want to be able to set...

```
dataDiskSizeGb: 100
dataDiskType: PD_SSD
storageAutoResize: true
failoverReplica:
    name: xxx
maintenanceWindow:
    day: 2
    hour: 10
```

Do you need external contributions around it or is there work underway to make these updates?
